(** Load per-rule contracts from [specs/rules/rule_contracts.json].

    Replaces [Validator_dag.default_meta] in validators.ml (PR #237, memo §10,
    §15.4). Contracts drive:
    - DAG edges (via consumes/provides/depends_on)
    - execution class routing (A/B/C/D)
    - proof-class classification (faithful/conservative/conditional)
    - project-scope filtering (lp_core_or_extended / any)

    The JSON mirror is generated by [scripts/tools/generate_rule_contracts.py]
    from the YAML source of truth. CI enforces parity.

    Looks up the JSON file from: (1) [$LP_RULE_CONTRACTS_JSON] env var, (2)
    [specs/rules/rule_contracts.json] relative to repo root, or (3) the embedded
    fallback (empty). *)

type execution_class = A | B | C | D
type proof_class = Formal_faithful | Formal_conservative | Formal_conditional

type evidence_class =
  | Source_pattern
  | Statistical_ml_bounded
  | Compile_log_evidence
  | External_binary

type project_scope = Lp_core_or_extended | Any_tier
type fix_scope = Local | Document

type contract = {
  rule_id : string;
  layer : Validator_dag.phase;
  execution_class : execution_class;
  proof_class : proof_class;
  evidence_class : evidence_class;
  consumes : string list;
  provides : string list;
  depends_on : string list;
  conflicts_with : string list;
  fix_scope : fix_scope;
  project_scope : project_scope;
}

exception Rule_contracts_missing of string
(** Raised by {!load} when the contract file is missing or malformed. PR #241
    (p1.1-#4): this is fatal at startup — the previous silent empty-list
    fallback could mask a broken deploy where every rule would run with empty
    DAG edges. *)

val load : unit -> contract list
(** Load contracts. Memoised: subsequent calls return the cached list.
    @raise Rule_contracts_missing
      if the JSON mirror cannot be found at any candidate path, or if it fails
      to parse. *)

val find_opt : string -> contract option
(** [find_opt rule_id] returns the contract for [rule_id], or [None]. *)

val count : unit -> int
(** Number of contracts currently loaded (0 if load failed silently). *)

val to_validator_meta : contract -> Validator_dag.validator_meta
(** Convert a contract to a [Validator_dag.validator_meta] consumed by
    [Validator_dag.build_dag]. *)

val execution_class_to_string : execution_class -> string
(** [execution_class_to_string] returns the canonical single-letter ID. *)

val proof_class_to_string : proof_class -> string
