(** * Strict.ExtractBytes — Coq→OCaml extraction of the decision on bytes.

    Emits, by Coq's extraction, [decide_bytes] (DecideBytes.v) and everything
    it depends on: the lexer [lex] (Lexer.v), the parser [parse] (Front.v),
    the phase-1 kernel [run]/[step] (Decide.v) it runs, and [rd], the reader
    extent that locates a NOT-READY; plus the diagnostic [explain]
    (Explain.v).  The committed copy is
    latex-parse/strict/strict_bytes_extracted.ml, regenerated by
    scripts/tools/regen_strict_bytes_extract.sh; its drift from these proofs
    is caught by scripts/tools/check_extract_identity.py (proof CI).

    It is a SEPARATE extraction from Extract.v (the phase-1 tree decider,
    latex-parse/strict/strict_kernel_extracted.ml), which stays byte for byte
    as phase 1 committed it: the phase-1 evidence (signatures, rule probes,
    differential) records that file's sha256, and nothing of phase 1 changes
    in phase 2.  The kernel functions appear in both extractions, each the
    extraction of the same Coq definitions.

    ── nat mapping ─────────────────────────────────────────────────────
    [nat] is extracted to OCaml [int] (ExtrOcamlNatInt; OPEN-096).  The nats
    here are token positions, line numbers, byte offsets and lengths: every
    one starts at 0 or 1 and changes only by successor or [pred] of a
    positive value (DecideBytes.rd_pos), and every constant is a product of
    small literals ([max_line_bytes], [max_file_bytes]).  [ascii_of_nat] is
    applied only to 10, 13 and 32.  [ascii] is extracted to OCaml [char]
    (ExtrOcamlChar). *)

From Coq Require Import Extraction.
From Coq Require Import ExtrOcamlBasic.
From Coq Require Import ExtrOcamlNatInt.
From Coq Require Import ExtrOcamlChar.
From Coq Require Import ExtrOcamlString.

From LaTeXPerfectionist.Strict Require Import
  Syntax Contract Semantics Decide Lexer Front DecideBytes Explain.

Extraction Language OCaml.
Unset Extraction Optimize.

Extraction "strict_bytes_extracted.ml"
  decide_bytes explain parse lex in_strict_bytes_b rd run step init toks_of
  tok_ok scripts_ok bounded in_math wfa scan_run rd_scan.
