(** * Strict.Extract — Coq→OCaml extraction of the L_S0 kernel.

    Emits, by Coq's extraction, the decider [decide], the byte printer
    [render] and everything they depend on ([flatten_doc], [in_strict_b],
    [step], [run], the grammar and contract types).  The committed copy is
    latex-parse/strict/strict_kernel_extracted.ml, regenerated by
    scripts/tools/regen_strict_kernel_extract.sh; drift between it and these
    proofs is caught by scripts/tools/check_extract_identity.py (proof CI).

    The extracted [decide] is what scripts/tools/strict_differential.py runs
    (through latex-parse/strict/strict_decide.ml) against the pinned oracle,
    and the extracted [render] produces the very bytes the oracle grades, so
    the differential tests the functions [strict_decider_exact] and
    [strict_ready_iff_pdflatex] are about, not a mirror of them.  Phase 1
    wires nothing into the product CLI (the strict tier stays a stub there,
    ADR-012 M0/M2).

    ── nat mapping ─────────────────────────────────────────────────────
    [nat] is extracted to OCaml [int] (ExtrOcamlNatInt; OPEN-096).  The only
    nats of the kernel are token positions: [init] starts at 0 and every
    change is a successor, so every value is a non-negative int bounded by
    the length of the token list.  No [Nat.pow], subtraction or division is
    reached.  [ascii] is extracted to OCaml [char] (ExtrOcamlChar), whose
    [Ascii.compare] realisation is the byte order the proofs use. *)

From Coq Require Import Extraction.
From Coq Require Import ExtrOcamlBasic.
From Coq Require Import ExtrOcamlNatInt.
From Coq Require Import ExtrOcamlChar.
From Coq Require Import ExtrOcamlString.

From LaTeXPerfectionist.Strict Require Import Syntax Contract Semantics Decide.

Extraction Language OCaml.
Unset Extraction Optimize.

Extraction "strict_kernel_extracted.ml"
  decide render flatten_doc in_strict_b run step init.
