version: '3.8'

services:
  latex-perfectionist:
    build:
      context: .
      target: application
    volumes:
      - ./documents:/app/input:ro
      - ./output:/app/output:rw
      - ./cache:/app/cache:rw
    environment:
      - LATEX_PERFECTIONIST_PROFILE=article
      - LATEX_PERFECTIONIST_CONFIG=/app/config/config.toml
    command: ["check", "/app/input"]

  latex-perfectionist-dev:
    build:
      context: .
      target: application
    volumes:
      - .:/app:rw
      - ./cache:/app/cache:rw
    environment:
      - LATEX_PERFECTIONIST_DEV=true
    working_dir: /app
    command: ["--help"]
    ports:
      - "8000:8000"  # For development server if needed

  latex-perfectionist-ci:
    build:
      context: .
      target: ci-runner
    volumes:
      - .:/app:rw
      - ./test-results:/app/test-results:rw
    environment:
      - CI=true
      - PYTEST_ARGS="-v --cov=latex_perfectionist --cov-report=xml"
    command: ["python", "-m", "pytest"]