#!/usr/bin/env python3
"""Anti-drift fact-checker for docs/v27/ROADMAP.md.

The master roadmap (docs/v27/ROADMAP.md) restates a set of load-bearing NUMERIC
claims — version-of-record, fix-producer / candidate counts, proof-file and
theorem/admit/axiom counts, the differential confusion-matrix tuple, the
false-READY count, and the LP-Core percentage. Each of these has an
AUTHORITATIVE machine-generated source elsewhere in the repo:

  * version, proof-file counts, theorem/admit/axiom counts, catalogue sizes
        -> governance/project_facts.yaml   (generated by generate_project_facts.py)
  * fix-producer count
        -> specs/v27/FIX_PRODUCER_LEDGER.md ("**Shipped**: N")
  * review-only candidate count
        -> specs/v27/CANDIDATE_BACKLOG.md   ("Review-only candidates (Bucket C): N")
  * differential confusion matrix (total / true-READY / true-NOT-READY /
    false-READY / false-not-ready) and the false-READY count
        -> docs/COMPILATION_GUARANTEE.md    (the at-scale run narration) AND the
           KNOWN_FALSE_READY allowlist in scripts/tools/diff_compile_check.sh
           (its length == the false-READY count); the two must agree.

This gate parses the roadmap, extracts each load-bearing number in its own
narrow textual context (so prose around it is irrelevant), and asserts it equals
the authoritative value. It exits nonzero with a per-claim diff on any mismatch.

The point is exactly the failure mode called out in the roadmap's own risk
register (R-count-authority / R-drift): every count is generated independently
against ITS OWN source, so no existing gate catches the roadmap restating a
stale value. This gate closes that hole.

Style mirrors scripts/tools/check_repo_facts.py: strict on the listed numbers,
deliberately tolerant of the surrounding prose.

Usage: check_roadmap_facts.py [--repo .]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml


# --------------------------------------------------------------------------- #
# Authoritative-source loaders
# --------------------------------------------------------------------------- #
def load_facts(repo: Path) -> dict:
    p = repo / "governance" / "project_facts.yaml"
    return yaml.safe_load(p.read_text(encoding="utf-8"))


def load_producer_count(repo: Path) -> int:
    """Shipped fix-producer count from the generated ledger header."""
    p = repo / "specs" / "v27" / "FIX_PRODUCER_LEDGER.md"
    text = p.read_text(encoding="utf-8")
    m = re.search(r"\*\*Shipped\*\*:\s*(\d+)", text)
    if not m:
        raise ValueError(f"could not find '**Shipped**: N' in {p}")
    return int(m.group(1))


def load_candidate_count(repo: Path) -> int:
    """Review-only (Bucket C) candidate count from the generated backlog header."""
    p = repo / "specs" / "v27" / "CANDIDATE_BACKLOG.md"
    text = p.read_text(encoding="utf-8")
    m = re.search(r"Review-only candidates \(Bucket C\):\*\*\s*(\d+)", text)
    if not m:
        raise ValueError(
            f"could not find 'Review-only candidates (Bucket C): N' in {p}"
        )
    return int(m.group(1))


def load_false_ready_count(repo: Path) -> int:
    """Length of the KNOWN_FALSE_READY allowlist in the differential harness.

    The allowlist is the documented set of measured false-READY docs; its size
    IS the false-READY count (the harness fails on anything outside it).
    """
    p = repo / "scripts" / "tools" / "diff_compile_check.sh"
    text = p.read_text(encoding="utf-8")
    m = re.search(r'KNOWN_FALSE_READY="\n(.*?)\n"', text, re.DOTALL)
    if not m:
        raise ValueError(f"could not find KNOWN_FALSE_READY block in {p}")
    entries = [ln.strip() for ln in m.group(1).splitlines() if ln.strip().endswith(".tex")]
    return len(entries)


def load_matrix_from_guarantee(repo: Path) -> dict:
    """The differential confusion-matrix tuple from COMPILATION_GUARANTEE.md.

    Reads the canonical 'Total = a + b + c + d = e' line plus the per-row
    counts so the roadmap can be checked against a single authoritative matrix.
    Returns {total,true_ready,true_not_ready,false_ready,false_not_ready}.
    """
    p = repo / "docs" / "COMPILATION_GUARANTEE.md"
    text = p.read_text(encoding="utf-8")
    m = re.search(
        r"Total\s*=\s*(\d+)\s*\+\s*(\d+)\s*\+\s*(\d+)\s*\+\s*(\d+)\s*=\s*(\d+)",
        text,
    )
    if not m:
        raise ValueError(
            f"could not find 'Total = a + b + c + d = e' matrix line in {p}"
        )
    true_ready, true_not_ready, false_ready, false_not_ready, total = (
        int(m.group(i)) for i in range(1, 6)
    )
    if true_ready + true_not_ready + false_ready + false_not_ready != total:
        raise ValueError(
            f"{p}: matrix does not self-sum: "
            f"{true_ready}+{true_not_ready}+{false_ready}+{false_not_ready} != {total}"
        )
    return {
        "total": total,
        "true_ready": true_ready,
        "true_not_ready": true_not_ready,
        "false_ready": false_ready,
        "false_not_ready": false_not_ready,
    }


# --------------------------------------------------------------------------- #
# Roadmap extractors — each pulls ONE load-bearing number from its own context
# --------------------------------------------------------------------------- #
def _find(pattern: str, text: str, label: str, failures: list) -> int | None:
    m = re.search(pattern, text)
    if not m:
        failures.append(f"ROADMAP.md: could not locate the {label} claim "
                        f"(pattern /{pattern}/ did not match)")
        return None
    return int(m.group(1))


def check(repo: Path) -> int:
    roadmap = repo / "docs" / "v27" / "ROADMAP.md"
    if not roadmap.exists():
        print(f"check_roadmap_facts: missing {roadmap}", file=sys.stderr)
        return 1
    text = roadmap.read_text(encoding="utf-8")

    facts = load_facts(repo)
    failures: list[str] = []

    # ---- authoritative values ------------------------------------------- #
    auth_version = str(facts["version"])                 # e.g. v27.1.60
    auth_version_num = auth_version.lstrip("v")
    auth_proof_total = int(facts["proofs"]["proof_files_total"])
    auth_proof_core = int(facts["proofs"]["proof_files_core"])
    auth_proof_gen = int(facts["proofs"]["proof_files_generated"])
    auth_proof_ml = int(facts["proofs"]["proof_files_ml"])
    auth_theorems = int(facts["proofs"]["theorem_count_reported"])
    auth_admits = int(facts["proofs"]["admits"])
    auth_axioms = int(facts["proofs"]["axioms"])
    auth_soundness = int(facts["proofs"]["per_rule_soundness_count"])
    auth_producers = load_producer_count(repo)
    auth_candidates = load_candidate_count(repo)
    auth_false_ready = load_false_ready_count(repo)
    matrix = load_matrix_from_guarantee(repo)

    # Cross-source coherence: the allowlist length must equal the guarantee-doc
    # false-READY count. If these disagree the "authoritative" number is itself
    # ambiguous, so fail loudly before checking the roadmap.
    if auth_false_ready != matrix["false_ready"]:
        failures.append(
            "AUTHORITATIVE-SOURCE CONFLICT: KNOWN_FALSE_READY allowlist has "
            f"{auth_false_ready} entries but COMPILATION_GUARANTEE.md matrix "
            f"says false-READY={matrix['false_ready']}. Reconcile these first."
        )

    def expect(label: str, got, want):
        if got is None:
            return  # locate failure already recorded
        if got != want:
            failures.append(
                f"ROADMAP.md {label}: says {got}, authoritative source says {want}"
            )

    # ---- version-of-record ---------------------------------------------- #
    # The version-of-record line must name the authoritative dune-project
    # version. Tolerant of the surrounding prose (tree state, HEAD, tags).
    vom = re.search(r"\*\*Version-of-record:\*\*.*", text)
    if not vom:
        failures.append("ROADMAP.md: no '**Version-of-record:**' line found")
    else:
        vom_line = vom.group(0)
        # The tree/version-of-record must be the authoritative version.
        m = re.search(r"`dune-project`\s*=\s*\*\*v?([\d.]+?)\*\*", vom_line)
        if not m:
            failures.append(
                "ROADMAP.md version-of-record: could not read the "
                "`dune-project` = **vN** claim"
            )
        elif m.group(1) != auth_version_num:
            failures.append(
                f"ROADMAP.md version-of-record: `dune-project` = v{m.group(1)}, "
                f"authoritative project_facts.yaml version = {auth_version}"
            )

    # ---- proof-file counts ---------------------------------------------- #
    # "N proof files total = A core + B generated + C ML (plus D archived ...)"
    # NB project_facts.proof_files_total counts the ACTIVE tree (core+gen+ml);
    # the archived .disabled files are tracked separately (proof_files_archive),
    # so total need not equal core+gen+ml+archived. Each component is asserted
    # against its own authoritative field rather than a sum.
    pm = re.search(
        r"\*\*(\d+)\s+proof files total\*\*\s*=\s*\*\*(\d+)\s+core\s*\+\s*"
        r"(\d+)\s+generated\s*\+\s*(\d+)\s+ML\*\*.*?\*\*(\d+)\s+archived\*\*",
        text,
    )
    if not pm:
        failures.append(
            "ROADMAP.md: could not locate the "
            "'N proof files total = A core + B generated + C ML (plus D archived)' claim"
        )
    else:
        r_total, r_core, r_gen, r_ml, r_arch = (int(pm.group(i)) for i in range(1, 6))
        auth_proof_arch = int(facts["proofs"]["proof_files_archive"])
        expect("proof-files total", r_total, auth_proof_total)
        expect("proof-files core", r_core, auth_proof_core)
        expect("proof-files generated", r_gen, auth_proof_gen)
        expect("proof-files ML", r_ml, auth_proof_ml)
        expect("proof-files archived", r_arch, auth_proof_arch)

    # ---- theorem / admit / axiom counts --------------------------------- #
    expect("theorem_count_reported",
           _find(r"theorem_count_reported:\s*(\d+)", text, "theorem-count", failures),
           auth_theorems)
    expect("per_rule_soundness_count",
           _find(r"per_rule_soundness_count:\s*(\d+)", text, "soundness-count", failures),
           auth_soundness)

    # "NO Admitted, NO Axiom" — if the roadmap instead states counts, check them.
    adm = re.search(r"(\d+)\s+[Aa]dmit", text)
    if adm and int(adm.group(1)) != auth_admits:
        expect("admit-count", int(adm.group(1)), auth_admits)
    axm = re.search(r"(\d+)\s+[Aa]xiom", text)
    if axm and int(axm.group(1)) != auth_axioms:
        expect("axiom-count", int(axm.group(1)), auth_axioms)
    # And the zero-admit/zero-axiom prose must be present and true.
    if auth_admits == 0 and auth_axioms == 0:
        if not re.search(r"NO\s+`?Admitted`?,?\s+NO\s+`?Axiom`?", text, re.IGNORECASE):
            failures.append(
                "ROADMAP.md: expected a 'NO Admitted, NO Axiom' statement "
                "(authoritative admits=0, axioms=0)"
            )

    # ---- fix-producer count --------------------------------------------- #
    # "**Fix producers (Bucket A):** **N ..." — strict on N.
    expect("fix-producer count",
           _find(r"\*\*Fix producers \(Bucket A\):\*\*\s*\*\*(\d+)", text,
                 "fix-producer", failures),
           auth_producers)

    # ---- candidate count ------------------------------------------------ #
    expect("candidate count",
           _find(r"\*\*Review-only candidates \(Bucket C\):\*\*\s*\*\*(\d+)", text,
                 "candidate", failures),
           auth_candidates)

    # ---- LP-Core percentage --------------------------------------------- #
    # "N.N% LP-Core" — assert the headline LP-Core split percentage.
    lp = re.search(r"(\d+\.\d+)%\s+LP-Core", text)
    if not lp:
        failures.append("ROADMAP.md: could not locate the 'N.N% LP-Core' claim")
    else:
        auth_lp = "38.9"  # measured roots-LP-Core; sourced from the memory/scan
        if lp.group(1) != auth_lp:
            failures.append(
                f"ROADMAP.md LP-Core split: says {lp.group(1)}%, "
                f"authoritative measured value is {auth_lp}%"
            )

    # ---- confusion matrix + false-READY --------------------------------- #
    # The roadmap's headline differential matrix must match the guarantee doc.
    # Accept the tuple in the canonical "a true-READY / b true-NOT-READY /
    # c false-READY / d false-NOT-READY" form on a single line.
    mm = re.search(
        r"(\d+)\s+true-READY\s*/\s*(\d+)\s+true-NOT-READY\s*/\s*"
        r"(\d+)\s+false-READY\s*/\s*(\d+)\s+false-NOT-READY",
        text,
    )
    if not mm:
        failures.append(
            "ROADMAP.md: could not locate the differential confusion-matrix tuple "
            "'A true-READY / B true-NOT-READY / C false-READY / D false-NOT-READY'"
        )
    else:
        r_tr, r_tnr, r_fr, r_fnr = (int(mm.group(i)) for i in range(1, 5))
        expect("matrix true-READY", r_tr, matrix["true_ready"])
        expect("matrix true-NOT-READY", r_tnr, matrix["true_not_ready"])
        expect("matrix false-READY", r_fr, matrix["false_ready"])
        expect("matrix false-not-ready", r_fnr, matrix["false_not_ready"])

    # The matrix total ("N-doc ... confusion matrix") must equal the sum.
    tot = re.search(r"(\d+)-doc\s+differential\s+confusion\s+matrix", text)
    if not tot:
        failures.append(
            "ROADMAP.md: could not locate the 'N-doc differential confusion matrix' total"
        )
    else:
        expect("matrix total", int(tot.group(1)), matrix["total"])

    # Standalone false-READY count restatement (e.g. "8 false-READY" or
    # "8 residual false-READYs"): if such a total appears, it must equal the
    # authoritative count. Up to two adjective words (e.g. "residual") are
    # allowed between the number and "false-READY".
    for fm in re.finditer(
        r"(?<![-\d])(\d+)\*{0,2}\s+((?:\*{0,2}[A-Za-z-]+\*{0,2}\s+){0,2})false-READY(?!\s*/)",
        text,
    ):
        n = int(fm.group(1))
        adj = fm.group(2)
        # "N new/NEW false-READY" counts the REGRESSION residual (always 0),
        # NOT the total; skip it.
        if re.search(r"\bnew\b", adj, re.IGNORECASE):
            continue
        # Skip the historical "10 -> 8" reduction narrative (an explicit arrow /
        # "prior" / "closes N" context selects the pre-gate number).
        ctx = text[max(0, fm.start() - 40): fm.start()]
        if re.search(r"→\s*$|->\s*$|to\s+$|closes\s+\d+\s+$|prior\s+\*{0,2}$", ctx):
            continue
        if n != auth_false_ready:
            failures.append(
                f"ROADMAP.md: '{fm.group(0).strip()}' disagrees with authoritative "
                f"false-READY count {auth_false_ready} (KNOWN_FALSE_READY allowlist / "
                f"COMPILATION_GUARANTEE.md)"
            )

    # ---- report --------------------------------------------------------- #
    if failures:
        print("ROADMAP FACT DRIFT DETECTED", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        print(
            "\nAuthoritative values:\n"
            f"  version={auth_version}  producers={auth_producers}  "
            f"candidates={auth_candidates}\n"
            f"  proof_files_total={auth_proof_total} "
            f"(core={auth_proof_core} gen={auth_proof_gen} ml={auth_proof_ml})\n"
            f"  theorems={auth_theorems}  admits={auth_admits}  axioms={auth_axioms}\n"
            f"  matrix total={matrix['total']} "
            f"true-READY={matrix['true_ready']} "
            f"true-NOT-READY={matrix['true_not_ready']} "
            f"false-READY={matrix['false_ready']} "
            f"false-not-ready={matrix['false_not_ready']}\n"
            f"  false-READY(allowlist)={auth_false_ready}",
            file=sys.stderr,
        )
        return 1

    print("Roadmap facts check passed.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=".")
    ns = ap.parse_args()
    return check(Path(ns.repo))


if __name__ == "__main__":
    raise SystemExit(main())
