#!/usr/bin/env python3
"""Generate the MEASURED-POSITION block of docs/v27/PROJECT_STATE.md.

Why this exists. docs/v27/ROADMAP.md carried hand-typed numbers and they rotted:
its banner, its false-READY count, its "0 over-rejection" claim and its
version-of-record were each factually false while check_roadmap_facts.py
reported "Roadmap facts check passed" -- that gate asserts only the numbers it
knows about, and uses re.search, so of two contradictory matrices only the first
was ever checked.

The lesson is not "write a better gate". It is that a number stated by hand in
prose WILL drift. So every number in PROJECT_STATE.md's position table is
generated from the artefact that owns it, and check_project_state.py regenerates
and diffs -- the same authenticity pattern check_release_integrity.py already
applies to project_facts.yaml.

Sources, one owner per fact:
  corpora/false_ready/manifest.json     fixture baseline           (quantity b)
  corpora/apply_fixes/manifest.json     fixer residual damage
  corpora/real_roots/results.json       real-paper matrix          (quantity c)
  scripts/tools/diff_compile_check.sh   differential allowlist     (quantity a)
  governance/project_facts.yaml         version, proof counts
  .github/required-status-checks.json   required CI contexts
  git describe --tags                   release debt

Usage:  gen_project_state.py [--repo .]           print the block
        gen_project_state.py --write              splice it into PROJECT_STATE.md
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN GENERATED: measured-position -->"
END = "<!-- END GENERATED: measured-position -->"
DOC = Path("docs/v27/PROJECT_STATE.md")


def allowlist_count(repo: Path) -> int:
    t = (repo / "scripts/tools/diff_compile_check.sh").read_text()
    m = re.search(r'KNOWN_FALSE_READY="\n(.*?)\n"', t, re.DOTALL)
    if not m:
        raise SystemExit("FATAL: KNOWN_FALSE_READY block not found")
    return len([l for l in m.group(1).splitlines() if l.strip().endswith(".tex")])


def build(repo: Path) -> str:
    fr = json.loads((repo / "corpora/false_ready/manifest.json").read_text())
    # A fixture whose expected_cli is READY is a LIVE false-READY only when
    # pdflatex REJECTS it. Rows graded `compiles` are ACCEPT-PINS: pdflatex
    # accepts them and READY is the CORRECT verdict, so counting them as
    # "known false-READYs" overstated row (b) by the number of accept-pins
    # (14 of 29 at the time this was fixed). This is the same rule
    # check_known_false_ready.py and manifest.baseline.false_ready_total use;
    # they had drifted apart from this generator.
    live = [f for f in fr["fixtures"]
            if f["expected_cli"] == "READY" and f.get("pdflatex") != "compiles"]
    accept_pins = [f for f in fr["fixtures"]
                   if f["expected_cli"] == "READY" and f.get("pdflatex") == "compiles"]
    af = json.loads((repo / "corpora/apply_fixes/manifest.json").read_text())
    kb = af["known_broken"]

    rr_path = repo / "corpora/real_roots/results.json"
    rr = json.loads(rr_path.read_text()) if rr_path.is_file() else None

    facts = {}
    for line in (repo / "governance/project_facts.yaml").read_text().splitlines():
        m = re.match(r"^(version|release_date):\s*'?([^'\s]+)'?", line)
        if m:
            facts[m.group(1)] = m.group(2)

    req = json.loads((repo / ".github/required-status-checks.json").read_text())["checks"]
    # DELIBERATELY NOT INCLUDED: `git describe --tags` commit distance.
    #
    # It is the natural way to show release debt, and it was in this block until
    # the gate immediately failed on the very next commit. A number that changes
    # on EVERY commit makes the regenerate-and-diff check fire on every PR, which
    # trains the reader to regenerate without looking -- and a gate people
    # silence is worse than one that never existed. The block below therefore
    # holds only facts that change when an ARTEFACT changes. Release debt is a
    # standing instruction in the prose instead: run `git describe --tags`.

    L = [BEGIN, "",
         "> Generated by `scripts/tools/gen_project_state.py`. **Do not hand-edit.**",
         "> `check_project_state.py` regenerates this block and fails on any diff,",
         "> so a number here can only be wrong if its source artefact is wrong.", ""]

    L += ["### The three quantities that must never be conflated", "",
          "Each grades a different corpus. They are disjoint. Conflating them is the",
          "single most repeated error in this project's history.", "",
          "| | corpus | value | what moves it |",
          "|---|---|---|---|"]
    # Count the documents the DIFFERENTIAL GRADES — that is what row (a)
    # describes. diff_compile_check.sh:125-130 enumerates `*.tex` and skips only
    # `*_part.tex` (\input children); fail_no_documentclass.tex IS graded (it is
    # a deliberately-failing fixture), so the denominator is 65, not the 64
    # files that contain a literal \documentclass.
    #
    # ⚠ THIS LINE HAS NOW BEEN WRONG TWICE, ONCE IN EACH DIRECTION (C-29).
    # v1 tested the SUBSTRING "documentclass" and published 65 — the right
    # number by accident, because fail_no_documentclass.tex says "There is no
    # documentclass here" in PROSE. v2 "fixed" it to a \\documentclass regex
    # and published 64 — a defensible-looking derivation of the WRONG quantity,
    # shipped inside a commit titled "three honesty defects". The number is not
    # "files containing \documentclass"; it is "documents the matrix grades".
    # Derive it by the SAME RULE the differential uses, and pin the semantic
    # with an assertion so the two scripts cannot drift apart silently.
    cc_dir = repo / "corpora/compile_check"
    graded = [f for f in cc_dir.glob("*.tex") if not f.name.endswith("_part.tex")]
    n_cc = len(graded)
    assert (cc_dir / "fail_no_documentclass.tex") in graded, (
        "semantic pin: fail_no_documentclass.tex is a GRADED document "
        "(diff_compile_check.sh skips only *_part.tex); if this fires, the "
        "enumeration rules have drifted apart — reconcile them, do not delete me")
    L.append(f"| **(a)** differential allowlist | `corpora/compile_check`, {n_cc} "
             f"hand-authored docs | **{allowlist_count(repo)}** | S6/S7-style detectors |")
    sf = sum(1 for f in live if f["pdflatex"] == "strong-fatal")
    eh = sum(1 for f in live if f["pdflatex"] == "error-halt")
    L.append(f"| **(b)** fixture baseline | `corpora/false_ready`, {len(fr['fixtures'])} fixtures "
             f"| **{len(live)}** ({sf} strong-fatal, {eh} error-halt; "
             f"{len(accept_pins)} accept-pins excluded) | R7 fix ranks |")
    if rr:
        c = rr["counts"]
        graded = sum(v for k, v in c.items() if not k.startswith("ungraded"))
        L.append(f"| **(c)** **real papers** | `corpora/real_roots`, {rr['frame']['n']} arXiv trees "
                 f"(frame {rr['frame']['frame_size']}) | **{c.get('FALSE-READY',0)} / {graded} = "
                 f"{100*c.get('FALSE-READY',0)/graded:.1f}%** | the SOUNDNESS CONSTRAINT "
                 f"of the North-Star metric (see below) |")
    L.append("")

    if rr:
        c = rr["counts"]
        graded = sum(v for k, v in c.items() if not k.startswith("ungraded"))
        ok = c.get("true-READY", 0) + c.get("true-NOT-READY", 0)
        fnr = c.get("false-NOT-READY", 0)
        nr = fnr + c.get("true-NOT-READY", 0)
        L += ["### Real-paper position", "",
              f"Oracle `{rr['oracle']['version']}`, {rr['oracle']['distribution']}, "
              f"protocol `{rr['oracle']['protocol']}`.", "",
              "| cell | n |", "|---|---|"]
        for k in ("true-READY", "true-NOT-READY", "FALSE-READY", "false-NOT-READY",
                  "ungraded-infra", "ungraded-timeout"):
            L.append(f"| {k} | {c.get(k, 0)} |")
        L += ["",
              f"- **Correct verdicts: {ok}/{graded} = {100*ok/graded:.1f}%**",
              f"- **Over-rejection: {fnr}/{graded} = {100*fnr/graded:.1f}%** — i.e. "
              f"**{100*fnr/nr:.1f}% of every NOT-READY verdict issued on a real paper is wrong**",
              f"- **False-READY: {c.get('FALSE-READY',0)}/{graded} = "
              f"{100*c.get('FALSE-READY',0)/graded:.1f}%**, against a definition requiring zero",
              ""]

    # ── THE NORTH-STAR METRIC ITSELF ────────────────────────────────────
    # ROADMAP.md: "Proven-verdict coverage at ZERO false-READY on a committed
    # corpus = (real papers that get a *proven* verdict matching pdflatex,
    # with zero false-READY) / (all real papers)."  Until 2026-09-04 this
    # block published three EMPIRICAL rates and never the metric, so eight
    # consecutive PRs optimised a proxy. It is generated here, from committed
    # per-document artefacts, so it cannot be quietly replaced again.
    def proven_block(path, label):
        f = repo / path
        if not f.is_file():
            return []
        raw = json.loads(f.read_text())
        # Phase A: the artefact gained provenance + summary; rows moved under
        # a key. Accept both shapes so a stale artefact fails LOUDLY on the
        # count rather than silently reading zero rows.
        rows = raw["rows"] if isinstance(raw, dict) else raw
        n = len(rows)
        certified_ok = sum(1 for r in rows
                           if r.get("model") == "certified" and r["cell"] == "true-READY")
        core_ok = sum(1 for r in rows
                      if r.get("model") == "certified" and r["cell"] == "true-READY"
                      and r.get("profile") == "lp-core")
        heur = sum(1 for r in rows if r.get("model") != "certified" and r.get("ready"))
        fr_cert = sum(1 for r in rows
                      if r["cell"] == "FALSE-READY" and r.get("model") == "certified")
        return [f"| {label} | {core_ok}/{n} = {100*core_ok/n:.1f}% | "
                f"{certified_ok}/{n} = {100*certified_ok/n:.1f}% | {heur} | {fr_cert} |"]

    pb = proven_block("corpora/real_roots/proven_coverage_sample1.json",
                      "sample 1 (tuned)")
    pb += proven_block("corpora/real_roots/proven_coverage_sample2.json",
                       "**sample 2 (virgin)**")
    if pb:
        L += ["### Premise-certified coverage — THE North-Star metric", "",
              "The ROADMAP calls this *proven-verdict coverage*. It is "
              "published here as **premise-certified** coverage, because that "
              "is what the artefact measures and what the CLI now prints: the "
              "Coq-extracted checker certified its PREMISES over the abstract "
              "model (`PREMISE-CERTIFIED`) **and** pdflatex compiled the "
              "document. It is not a proof that the document compiles — "
              "measured, that reading is wrong on 5.0% of certified real "
              "papers, and 5.7% when restricted to LP-Core, so scoping the "
              "claim to the proven subset makes it MORE wrong, not less. The "
              "guarantee doc scopes the claim to LP-Core, so that column is "
              "the number this project may publish.",
              "",
              "| corpus | premise-certified (LP-Core) | certified (any tier) | uncertified READYs | certified FALSE-READY |",
              "|---|---|---|---|---|"] + pb + [""]

    # ── OUT-OF-SAMPLE POSITION ──────────────────────────────────────────
    s2_path = repo / "corpora/real_roots/results_sample2.json"
    if s2_path.is_file():
        s2 = json.loads(s2_path.read_text())
        c2 = s2["counts"]
        g2 = sum(v for k, v in c2.items() if not k.startswith("ungraded"))
        ok2 = c2.get("true-READY", 0) + c2.get("true-NOT-READY", 0)
        L += ["### Out-of-sample position (sample 2 — VIRGIN)", "",
              "Ranks 201-400 of the same deterministic ordering. **No fix has "
              "ever been tuned against these documents.** Sample 1 is burned "
              "for soundness claims: every fix in the #565-#572 run was "
              "measured against it, so its false-READY rate is an optimistic "
              "estimate and must never be quoted alone.", "",
              "| cell | n |", "|---|---|"]
        for k in ("true-READY", "true-NOT-READY", "FALSE-READY", "false-NOT-READY",
                  "ungraded-infra"):
            L.append(f"| {k} | {c2.get(k, 0)} |")
        L += ["",
              f"- **Correct verdicts: {ok2}/{g2} = {100*ok2/g2:.1f}%**",
              f"- **False-READY: {c2.get('FALSE-READY',0)}/{g2} = "
              f"{100*c2.get('FALSE-READY',0)/g2:.1f}%** — the in-sample zero "
              f"does NOT generalise (OPEN-034)", ""]

    L += ["### Fixer residual (auto-fix channel)", "",
          "| property | rows |", "|---|---|"]
    for k in ("breaks_compile", "degrades_verdict", "not_idempotent", "manufactured_false_ready"):
        L.append(f"| `{k}` | {sum(1 for r in kb if r.get(k))} |")
    L += ["", f"Total recorded rows: **{len(kb)}**. "
              f"pdflatex-graded: `{af.get('pdflatex_graded')}`.", ""]

    L += ["### Infrastructure", "",
          f"- Required CI contexts: **{len(req)}** — {', '.join(sorted(c['context'] for c in req))}",
          f"- Version of record: **{facts.get('version','?')}** "
          f"(`project_facts.yaml` release_date {facts.get('release_date','?')})",
          "- Release debt: run `git describe --tags`. A distance greater than 0 "
          "means merged work is unreleased, and **no gate compares any version "
          "marker to a tag** (OPEN-013) — so this is the one number here you must "
          "check by hand.",
          "", END]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--write", action="store_true")
    ns = ap.parse_args()
    repo = Path(ns.repo).resolve()
    block = build(repo)
    if not ns.write:
        print(block)
        return 0
    doc = repo / DOC
    t = doc.read_text()
    if BEGIN not in t or END not in t:
        raise SystemExit(f"FATAL: markers missing in {DOC}")
    pre, rest = t.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    doc.write_text(pre + block + post)
    print(f"[gen-project-state] wrote the generated block into {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
