#!/usr/bin/env python3
"""Generate the MEASURED-POSITION block of docs/v27/PROJECT_STATE.md.

Why this exists. docs/v27/ROADMAP.md carried hand-typed numbers and they rotted:
its banner, its false-READY count, its "0 over-rejection" claim and its
version-of-record were each factually false while check_roadmap_facts.py
reported "Roadmap facts check passed" -- that gate asserts only the numbers it
knows about, and uses re.search, so of two contradictory matrices only the first
was ever checked.

The lesson is not "write a better gate". It is that a number stated by hand in
prose WILL drift. So every number in PROJECT_STATE.md's position table is
generated from the artefact that owns it, and check_project_state.py regenerates
and diffs -- the same authenticity pattern check_release_integrity.py already
applies to project_facts.yaml.

Sources, one owner per fact:
  corpora/false_ready/manifest.json     fixture baseline           (quantity b)
  corpora/apply_fixes/manifest.json     fixer residual damage
  corpora/real_roots/results.json       real-paper matrix          (quantity c)
  scripts/tools/diff_compile_check.sh   differential allowlist     (quantity a)
  governance/project_facts.yaml         version, proof counts
  .github/required-status-checks.json   required CI contexts
  git describe --tags                   release debt

Usage:  gen_project_state.py [--repo .]           print the block
        gen_project_state.py --write              splice it into PROJECT_STATE.md
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN GENERATED: measured-position -->"
END = "<!-- END GENERATED: measured-position -->"
DOC = Path("docs/v27/PROJECT_STATE.md")


def allowlist_count(repo: Path) -> int:
    t = (repo / "scripts/tools/diff_compile_check.sh").read_text()
    m = re.search(r'KNOWN_FALSE_READY="\n(.*?)\n"', t, re.DOTALL)
    if not m:
        raise SystemExit("FATAL: KNOWN_FALSE_READY block not found")
    return len([l for l in m.group(1).splitlines() if l.strip().endswith(".tex")])


def build(repo: Path) -> str:
    fr = json.loads((repo / "corpora/false_ready/manifest.json").read_text())
    live = [f for f in fr["fixtures"] if f["expected_cli"] == "READY"]
    af = json.loads((repo / "corpora/apply_fixes/manifest.json").read_text())
    kb = af["known_broken"]

    rr_path = repo / "corpora/real_roots/results.json"
    rr = json.loads(rr_path.read_text()) if rr_path.is_file() else None

    facts = {}
    for line in (repo / "governance/project_facts.yaml").read_text().splitlines():
        m = re.match(r"^(version|release_date):\s*'?([^'\s]+)'?", line)
        if m:
            facts[m.group(1)] = m.group(2)

    req = json.loads((repo / ".github/required-status-checks.json").read_text())["checks"]
    # DELIBERATELY NOT INCLUDED: `git describe --tags` commit distance.
    #
    # It is the natural way to show release debt, and it was in this block until
    # the gate immediately failed on the very next commit. A number that changes
    # on EVERY commit makes the regenerate-and-diff check fire on every PR, which
    # trains the reader to regenerate without looking -- and a gate people
    # silence is worse than one that never existed. The block below therefore
    # holds only facts that change when an ARTEFACT changes. Release debt is a
    # standing instruction in the prose instead: run `git describe --tags`.

    L = [BEGIN, "",
         "> Generated by `scripts/tools/gen_project_state.py`. **Do not hand-edit.**",
         "> `check_project_state.py` regenerates this block and fails on any diff,",
         "> so a number here can only be wrong if its source artefact is wrong.", ""]

    L += ["### The three quantities that must never be conflated", "",
          "Each grades a different corpus. They are disjoint. Conflating them is the",
          "single most repeated error in this project's history.", "",
          "| | corpus | value | what moves it |",
          "|---|---|---|---|"]
    L.append(f"| **(a)** differential allowlist | `corpora/compile_check`, 65 hand-authored docs "
             f"| **{allowlist_count(repo)}** | S6/S7-style detectors |")
    sf = sum(1 for f in live if f["pdflatex"] == "strong-fatal")
    eh = sum(1 for f in live if f["pdflatex"] == "error-halt")
    L.append(f"| **(b)** fixture baseline | `corpora/false_ready`, {len(fr['fixtures'])} fixtures "
             f"| **{len(live)}** ({sf} strong-fatal, {eh} error-halt) | R7 fix ranks |")
    if rr:
        c = rr["counts"]
        graded = sum(v for k, v in c.items() if not k.startswith("ungraded"))
        L.append(f"| **(c)** **real papers** | `corpora/real_roots`, {rr['frame']['n']} arXiv trees "
                 f"(frame {rr['frame']['frame_size']}) | **{c.get('FALSE-READY',0)} / {graded} = "
                 f"{100*c.get('FALSE-READY',0)/graded:.1f}%** | *the only one that is the North Star* |")
    L.append("")

    if rr:
        c = rr["counts"]
        graded = sum(v for k, v in c.items() if not k.startswith("ungraded"))
        ok = c.get("true-READY", 0) + c.get("true-NOT-READY", 0)
        fnr = c.get("false-NOT-READY", 0)
        nr = fnr + c.get("true-NOT-READY", 0)
        L += ["### Real-paper position", "",
              f"Oracle `{rr['oracle']['version']}`, {rr['oracle']['distribution']}, "
              f"protocol `{rr['oracle']['protocol']}`.", "",
              "| cell | n |", "|---|---|"]
        for k in ("true-READY", "true-NOT-READY", "FALSE-READY", "false-NOT-READY",
                  "ungraded-infra", "ungraded-timeout"):
            L.append(f"| {k} | {c.get(k, 0)} |")
        L += ["",
              f"- **Correct verdicts: {ok}/{graded} = {100*ok/graded:.1f}%**",
              f"- **Over-rejection: {fnr}/{graded} = {100*fnr/graded:.1f}%** — i.e. "
              f"**{100*fnr/nr:.1f}% of every NOT-READY verdict issued on a real paper is wrong**",
              f"- **False-READY: {c.get('FALSE-READY',0)}/{graded} = "
              f"{100*c.get('FALSE-READY',0)/graded:.1f}%**, against a definition requiring zero",
              ""]

    L += ["### Fixer residual (auto-fix channel)", "",
          "| property | rows |", "|---|---|"]
    for k in ("breaks_compile", "degrades_verdict", "not_idempotent", "manufactured_false_ready"):
        L.append(f"| `{k}` | {sum(1 for r in kb if r.get(k))} |")
    L += ["", f"Total recorded rows: **{len(kb)}**. "
              f"pdflatex-graded: `{af.get('pdflatex_graded')}`.", ""]

    L += ["### Infrastructure", "",
          f"- Required CI contexts: **{len(req)}** — {', '.join(sorted(c['context'] for c in req))}",
          f"- Version of record: **{facts.get('version','?')}** "
          f"(`project_facts.yaml` release_date {facts.get('release_date','?')})",
          "- Release debt: run `git describe --tags`. A distance greater than 0 "
          "means merged work is unreleased, and **no gate compares any version "
          "marker to a tag** (OPEN-013) — so this is the one number here you must "
          "check by hand.",
          "", END]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--write", action="store_true")
    ns = ap.parse_args()
    repo = Path(ns.repo).resolve()
    block = build(repo)
    if not ns.write:
        print(block)
        return 0
    doc = repo / DOC
    t = doc.read_text()
    if BEGIN not in t or END not in t:
        raise SystemExit(f"FATAL: markers missing in {DOC}")
    pre, rest = t.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    doc.write_text(pre + block + post)
    print(f"[gen-project-state] wrote the generated block into {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
