#!/usr/bin/env python3
"""Regenerate specs/v27/CANDIDATE_BACKLOG.md from GROUND TRUTH.

The backlog previously drifted: it listed ~45 rules as "deferred" that were
already wired as candidates. This script greps the OCaml validators for the
actual result-constructor each rule uses and emits an accurate, un-lie-able
status. Run it after any candidate/producer batch; a CI check compares its
output to the committed file.

Classification per rule id (by the constructor it calls):
  - producer     : mk_result_with_fix*        (Bucket A auto-fix)
  - candidate    : mk_result_with_candidates   (Bucket C review-only)
  - diagnose-only: mk_result (plain)           (no fix/candidate)

A small hand-maintained RECOVERABLE set records diagnose-only rules that an
audit found DO have a determinate bounded fix and should still be wired — kept
tiny and explicit so it is visible, not buried.
"""
import re
import sys
import glob
import os
from collections import defaultdict

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(REPO, "latex-parse", "src")
OUT = os.path.join(REPO, "specs", "v27", "CANDIDATE_BACKLOG.md")

# Diagnose-only rules an audit confirmed have a determinate, bounded fix and
# should be wired as candidates (or explicitly justified). Keep this list
# SHORT and current — remove ids as they are wired.
RECOVERABLE = {
    "MATH-056": "dedup repeated \\operatorname{f}: wrap first use + rewrite call sites (determinate)",
    "PKG-001": "duplicate \\usepackage: delete the later duplicate load (keep first)",
    "TAB-002": "\\caption after \\end{tabular}: move it above the tabular (determinate reposition)",
    "TAB-007": "text in numeric column: wrap the cell in \\multicolumn{1}{l}{...}",
    "TAB-011": "top/bottom \\hline: replace with \\toprule/\\bottomrule (booktabs)",
}


def classify():
    producer, candidate, diagnose = set(), set(), set()
    for f in glob.glob(os.path.join(SRC, "validators_*.ml")):
        s = open(f, encoding="utf-8").read()
        producer |= set(re.findall(r'mk_result_with_fix\w* ~id:"([A-Z0-9-]+)"', s))
        candidate |= set(re.findall(r'mk_result_with_candidates ~id:"([A-Z0-9-]+)"', s))
        diagnose |= set(re.findall(r'mk_result ~id:"([A-Z0-9-]+)"', s))
    diagnose -= producer | candidate
    return producer, candidate, diagnose


def fam(rid):
    return rid.rsplit("-", 1)[0]


def render():
    producer, candidate, diagnose = classify()
    by_fam_diag = defaultdict(list)
    for r in sorted(diagnose):
        by_fam_diag[fam(r)].append(r)
    L = []
    L.append("# Candidate Coverage Backlog — GROUND-TRUTH (generated)")
    L.append("")
    L.append("> Generated by `scripts/tools/gen_candidate_backlog.py` from the actual")
    L.append("> validator source. Do NOT hand-edit — run the script. A CI gate compares")
    L.append("> this file to the generator output so it can never drift again.")
    L.append("")
    L.append(f"**Auto-fix producers (Bucket A):** {len(producer)}  ")
    L.append(f"**Review-only candidates (Bucket C):** {len(candidate)}  ")
    L.append(f"**Diagnose-only:** {len(diagnose)}")
    L.append("")
    L.append("## Corrected candidate bar")
    L.append("")
    L.append("A rule is candidate-able iff its intended fix has a DETERMINATE, well-bounded")
    L.append("edit (render/locale/prose-changing is FINE — candidates are review-only, never")
    L.append("auto-applied). Cross-file renames are candidate-able as in-file multi-edit or")
    L.append("label-only candidates. Defer ONLY when there is genuinely no determinate target")
    L.append("(threshold with no canonical value; needs a dictionary/NLP the repo lacks;")
    L.append("ambiguous which-of-N target; whole-document consistency flag with no single site).")
    L.append("")
    L.append("## Known-recoverable (determinate fix, not yet wired)")
    L.append("")
    still = [r for r in RECOVERABLE if r in diagnose]
    if still:
        for r in sorted(still):
            L.append(f"- **{r}** — {RECOVERABLE[r]}")
    else:
        L.append("- (none — all previously-flagged recoverable rules are wired)")
    L.append("")
    L.append("## Diagnose-only by family (candidate-able subset already wired; rest are")
    L.append("genuinely non-candidate-able — thresholds / NLP / dictionary / ambiguous target)")
    L.append("")
    for f in sorted(by_fam_diag, key=lambda k: -len(by_fam_diag[k])):
        rs = by_fam_diag[f]
        L.append(f"- **{f}** ({len(rs)}): {', '.join(rs)}")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur.strip() != text.strip():
            print("[candidate-backlog] DRIFT: CANDIDATE_BACKLOG.md is stale; run "
                  "scripts/tools/gen_candidate_backlog.py", file=sys.stderr)
            sys.exit(1)
        print("[candidate-backlog] PASS: in sync with source")
        return
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"[candidate-backlog] wrote {OUT}")


if __name__ == "__main__":
    main()
