[package]
name = "l0_lexer_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread","macros","net","io-util","time"] }
bytes = "1"
byteorder = "1"
thiserror = "1"

[features]
default = []