(** * BodyTokenFrontEndExtract — Coq→OCaml extraction of the verified
    bytes→body_token front-end.

    This file emits, via Coq's certified extraction, an OCaml module containing
    [BodyTokenFrontEnd.body_of_source] together with every function it depends
    on (the label/ref scanners, the offset-sorted merge, the FNV-1a 30-bit
    hash, the feature detector, the blank test and the protected-range test).

    The OCaml runtime ([Compile_evidence.extract_body_verified]) EXECUTES this
    extracted code as the PRODUCTION bytes→body_token path, so the token list
    the capstone premise-checker consumes is produced by PROVEN code
    (governed by [scan_labels_sound]/[scan_labels_complete] +
    [scan_refs_sound]/[scan_refs_complete] + [merge_events_sorted] +
    [body_label_defs_of_source] + [body_required_features_of_source] +
    [compile_safe_of_source]; all Qed, 0 admits).

    Extraction touches only the computational content; it does not open or
    alter any proof.  [Print Assumptions compile_safe_of_source] remains
    "Closed under the global context" (executed in BodyTokenFrontEnd.v).

    ── nat mapping ─────────────────────────────────────────────────────
    [nat] is mapped to OCaml [int] (ExtrOcamlNatInt), exactly as in
    CompileGuaranteeExtract.v.  Most arithmetic (add/sub/mul/div2/eqb/leb/ltb)
    is realized natively by ExtrOcamlNatInt.  The FNV state stays ≤ 0x811c9dc5
    < 2^32 and the single product is < 2^55, comfortably inside OCaml's 63-bit
    int.

    ── 2^k constant realization (REQUIRED — see below) ─────────────────
    ExtrOcamlNatInt does NOT map [Nat.pow].  Without the directives below, the
    2^k constants ([two30 = 2 ^ 30], reached via [mod_two30]; and the [2^k]
    summands of [fnv_basis]/[fnv_prime]) extract to the *unary* recursive
    [Nat.pow], which multiplies via a re-extracted unary [mul] — so evaluating
    them at MODULE-INITIALISATION time materialises ~10^9 [succ] cells and
    blows the native stack before any code runs.  We therefore realize the
    three top-level hash constants directly as their native int literals.  This
    is sound and trivially checkable: each equals the value asserted
    ([2^30 = 1073741824]; [fnv_basis = 0x811c9dc5 = 2166136261];
    [fnv_prime = 0x01000193 = 16777619]) — exactly the constants the hand
    OCaml [Compile_evidence.label_id] uses, which the differential parity test
    then confirms byte-for-byte.  [Nat.pow] itself is also realized natively as
    a belt-and-suspenders defence against any other 2^k use. *)

From Coq Require Import Extraction.
From Coq Require Import ExtrOcamlBasic.
From Coq Require Import ExtrOcamlNatInt.

From LaTeXPerfectionist Require Import
  BuildProfileSound
  PdflatexModel
  BodyTokenFrontEnd.

Extraction Language OCaml.

(** Realize the three hash constants as native int literals (each provably
    equal to the value given; see the header note). This eliminates the
    module-init evaluation of the unary [Nat.pow]. *)
Extract Constant BodyTokenFrontEnd.two30 => "1073741824".
Extract Constant BodyTokenFrontEnd.fnv_basis => "2166136261".
Extract Constant BodyTokenFrontEnd.fnv_prime => "16777619".

(** Belt-and-suspenders: native [Nat.pow] for any other 2^k use. Iterative,
    native [*] on 63-bit ints. *)
Extract Constant Nat.pow =>
  "(fun b e -> let rec p acc i = if i <= 0 then acc else p (acc * b) (i - 1) in p 1 e)".

(** Keep the extracted code readable and inline-free so [Compile_evidence] can
    reference the generated types/functions by predictable names.  The file is
    emitted into the compilation cwd; the committed copy lives in
    [latex-parse/src/body_token_frontend_extracted.ml] and is regenerated by
    [scripts/tools/regen_body_token_frontend_extract.sh]. *)
Unset Extraction Optimize.

(** Recursive extraction pulls in every dependency:
    - data: [feature] [body_token] [scan_event]
    - scanners: [prefix_b] [first_match] [idx_close] [read_key] [scan_from]
                [scan_generic] [scan_labels] [scan_refs]
    - merge: [merge_fuel] [merge_events]
    - hash: [odd_b] [lxor_fuel] [lxor32] [shr_fuel] [mod_two30] [fnv_step]
            [fnv30]
    - features/blank: [contains_b] [detect_body_features] [is_ws] [is_blank]
    - ranges: [in_ranges_b]
    - the top-level [body_of_source]. *)
Extraction "body_token_frontend_extracted.ml"
  body_of_source scan_labels scan_refs merge_events fnv30
  detect_body_features is_blank in_ranges_b.
