(** * BodyTokenFrontEndExtract — Coq→OCaml extraction of the verified
    bytes→body_token front-end.

    This file emits, via Coq's certified extraction, an OCaml module containing
    [BodyTokenFrontEnd.body_of_source] together with every function it depends
    on (the label/ref scanners, the offset-sorted merge, the FNV-1a 30-bit
    hash, the feature detector, the blank test and the protected-range test).

    The OCaml runtime ([Compile_evidence.extract_body_verified]) EXECUTES this
    extracted code as the PRODUCTION bytes→body_token path, so the token list
    the capstone premise-checker consumes is produced by PROVEN code
    (governed by [scan_labels_sound]/[scan_labels_complete] +
    [scan_refs_sound]/[scan_refs_complete] + [merge_events_sorted] +
    [body_label_defs_of_source] + [body_required_features_of_source] +
    [compile_safe_of_source]; all Qed, 0 admits).

    Extraction touches only the computational content; it does not open or
    alter any proof.  [Print Assumptions compile_safe_of_source] remains
    "Closed under the global context" (executed in BodyTokenFrontEnd.v).

    ── nat mapping ─────────────────────────────────────────────────────
    [nat] is mapped to OCaml [int] (ExtrOcamlNatInt), exactly as in
    CompileGuaranteeExtract.v.  Every arithmetic operation the front-end
    performs is realized faithfully on non-negative ints: add/sub/mul/div2/
    eqb/leb/ltb.  The FNV state stays ≤ 0x811c9dc5 < 2^32 and the single
    product is < 2^55 ([BodyTokenFrontEnd.fnv_mul_bound]), comfortably inside
    OCaml's 63-bit int.  The 2^k constants extract to [Nat.pow] recursion on
    the (small) exponent — no gigantic unary numeral is ever built. *)

From Coq Require Import Extraction.
From Coq Require Import ExtrOcamlBasic.
From Coq Require Import ExtrOcamlNatInt.

From LaTeXPerfectionist Require Import
  BuildProfileSound
  PdflatexModel
  BodyTokenFrontEnd.

Extraction Language OCaml.

(** Keep the extracted code readable and inline-free so [Compile_evidence] can
    reference the generated types/functions by predictable names.  The file is
    emitted into the compilation cwd; the committed copy lives in
    [latex-parse/src/body_token_frontend_extracted.ml] and is regenerated by
    [scripts/tools/regen_body_token_frontend_extract.sh]. *)
Unset Extraction Optimize.

(** Recursive extraction pulls in every dependency:
    - data: [feature] [body_token] [scan_event]
    - scanners: [prefix_b] [first_match] [idx_close] [read_key] [scan_from]
                [scan_generic] [scan_labels] [scan_refs]
    - merge: [merge_fuel] [merge_events]
    - hash: [odd_b] [lxor_fuel] [lxor32] [shr_fuel] [mod_two30] [fnv_step]
            [fnv30]
    - features/blank: [contains_b] [detect_body_features] [is_ws] [is_blank]
    - ranges: [in_ranges_b]
    - the top-level [body_of_source]. *)
Extraction "body_token_frontend_extracted.ml"
  body_of_source scan_labels scan_refs merge_events fnv30
  detect_body_features is_blank in_ranges_b.
