(** * CompileGuaranteeExtract — Coq→OCaml extraction of the proven premise-checker.

    This file emits, via Coq's certified extraction, an OCaml module containing
    [CompileGuaranteeBridge.project_wf_dec] together with every data type and
    boolean sub-checker it depends on (edges_closed_b / valid_topo_b /
    nodup_nat_b / all_features_compatible and the [feature]/[engine]/[node]/
    [body_token]/[project]/[profile] models).

    The OCaml runtime ([Compile_evidence]) then EXECUTES this extracted code for
    the premise decision, so the [--compile-check MODEL-READY] verdict reflects
    the PROVEN checker (governed by [project_wf_dec_sound], Qed, 0 admits),
    rather than a hand-written OCaml mirror.

    Extraction touches only the computational content; it does not open or alter
    any proof.  [Print Assumptions project_wf_dec_compile_safe] remains "Closed
    under the global context".

    ── nat mapping ─────────────────────────────────────────────────────
    [nat] is mapped to OCaml [int]: label ids in the runtime are 30-bit FNV
    hashes (up to ~10^9), for which a Peano [nat] representation would be
    catastrophic.  The mapping is the standard, sound int-for-nat extraction:
    [O]→0, [S n]→n+1, [Nat.eqb]→[(=)], [Nat.ltb]→[(<)].  These are the ONLY
    arithmetic operations [project_wf_dec] (transitively) performs; each is
    faithful on non-negative ints, and every nat the checker constructs is a
    list index or a caller-supplied label id, all non-negative.  This is exactly
    the extraction Coq's standard library recommends (ExtrOcamlNatInt). *)

From Coq Require Import Extraction.
From Coq Require Import ExtrOcamlBasic.
From Coq Require Import ExtrOcamlNatInt.

From LaTeXPerfectionist Require Import
  ProjectClosure
  BuildProfileSound
  PdflatexModel
  CompileGuaranteeBridge.

Extraction Language OCaml.

(** Keep the extracted code readable and inline-free so [Compile_evidence] can
    reference the generated types/functions by predictable names.  The file is
    emitted into the compilation cwd; the committed copy lives in
    [latex-parse/src/compile_guarantee_extracted.{ml,mli}] and is regenerated by
    [scripts/tools/regen_compile_guarantee_extract.sh]. *)
Unset Extraction Optimize.

(** Recursive extraction of the checker pulls in every dependency:
    - data: [artefact_kind] [node] [build_graph] [engine] [feature]
            [body_token] [pdflatex_project] [pdflatex_profile]
    - checkers: [node_eqb] [node_in_b] [edges_closed_b] [index_of]
                [index_lt_b] [valid_topo_b] [project_closed_b]
                [mem_nat_b] [nodup_nat_b] [compatible] [all_features_compatible]
                [body_required_features] [body_label_defs]
    - the top-level [project_wf_dec]. *)
Extraction "compile_guarantee_extracted.ml" project_wf_dec.
