(** * LanguageContractExtract — Coq→OCaml extraction of the proven tier classifier.

    This file emits, via Coq's certified extraction, an OCaml module containing
    [LanguageContract.classify] together with every data type and boolean
    sub-checker it depends on ([tier] / [severity] / [feature] / [is_foreign] /
    [is_forbidden_core] / [any_foreign] / [any_forbidden_core]).

    The OCaml runtime ([Language_profile.classify_source]) then EXECUTES this
    extracted [classify] for the tier DECISION (feature-list -> tier), so the
    [LP-Core / LP-Extended / LP-Foreign] verdict reflects the PROVEN classifier
    (governed by [classify_lp_core_sound], Qed, 0 admits) rather than a
    hand-written OCaml mirror of the decision logic.

    The trusted boundary that remains is exactly the bytes->feature-list step
    ([Unsupported_feature.detect], a regex scan): that is adversarially certified
    by [test_language_contract_cert.ml], not formally verified.  The
    feature-list->tier step is now proven-executed.

    Extraction touches only the computational content; it does not open or alter
    any proof.  [Print Assumptions classify_lp_core_sound] remains "Closed under
    the global context".

    ── nat mapping ─────────────────────────────────────────────────────
    [feature.f_id] is a [nat] (a spec-level proxy for the string feature id).
    We map [nat] to OCaml [int] via the standard, sound [ExtrOcamlNatInt]
    extraction, exactly as [CompileGuaranteeExtract.v] does.  [classify] performs
    NO arithmetic on [f_id] — it only matches on [f_severity] — so the mapping is
    trivially faithful here; it is present solely so the [feature] record's
    [f_id] field extracts to a usable OCaml [int] rather than Peano [nat]. *)

From Coq Require Import Extraction.
From Coq Require Import ExtrOcamlBasic.
From Coq Require Import ExtrOcamlNatInt.

From LaTeXPerfectionist Require Import LanguageContract.

Extraction Language OCaml.

(** Keep the extracted code readable and inline-free so [Language_profile] can
    reference the generated types/functions by predictable names.  The file is
    emitted into the compilation cwd; the committed copy lives in
    [latex-parse/src/language_contract_extracted.ml] and is regenerated by
    [scripts/tools/regen_language_contract_extract.sh]. *)
Unset Extraction Optimize.

(** Recursive extraction of [classify] pulls in every dependency:
    - data: [tier] [severity] [feature]
    - checkers: [is_foreign] [is_forbidden_core] [any_foreign]
                [any_forbidden_core]
    - the top-level [classify]. *)
Extraction "language_contract_extracted.ml" classify.
