(* Unit tests of the EXTRACTED L_S0 decider (proofs/Strict), on documents whose
   pdflatex outcome was measured under the pinned oracle. Each case belongs to a
   probe family of corpora/strict_s0/rule_probes.json (named in the comment),
   where the oracle's rc, PDF, first error and line are recorded for that
   family's documents. These tests pin the extracted code to the measured
   behaviour; the differential (scripts/tools/strict_differential.py) is the
   broad check.

   The contract here is a TEST contract, not the committed one: three names with
   behaviours measured under the pinned oracle while the kernel was built
   (2026-09-27: [\alpha] in text gives "Missing $ inserted", [$\LaTeX$] gives
   "You can't use `\spacefactor' in math mode", [$x^a\relax^b$] gives "Double
   superscript"), plus two defined names without a signature. The kernel never
   sees a name except through such a record; the committed signatures
   (corpora/contracts/strict/article-s0-signatures.json) are generated by
   probes, independently of this file. *)

module K = Strict_kernel_extracted

let chars s = List.init (String.length s) (String.get s)

let str l =
  let b = Buffer.create 16 in
  List.iter (Buffer.add_char b) l;
  Buffer.contents b

let contract =
  let sigs =
    [
      ("alpha", { K.sig_text = K.TxFatal K.E3; K.sig_math = K.MxNoad });
      ("LaTeX", { K.sig_text = K.TxMaterial; K.sig_math = K.MxFatal K.E3 });
      ("relax", { K.sig_text = K.TxNoop; K.sig_math = K.MxNoop });
      ("quad", { K.sig_text = K.TxMaterial; K.sig_math = K.MxNoad });
    ]
  in
  (* Step 2, slice A: three one-argument commands, with the behaviours the cases
     below measured under the pinned oracle (2026-09-28): an error in
     [\textbf]'s argument is reported on the line of its closing brace, a
     paragraph break in it gives "Paragraph ended before \text@command was
     complete" there too; [\mathrm] in text gives "allowed only in math mode" on
     its own line, and a paragraph break in its argument "Paragraph ended before
     \math@egroup was complete" on the break's line; [\mbox] runs its argument
     in an hbox, where [$$] is an empty formula. *)
  let asigs =
    [
      ( "textbf",
        {
          K.as_long = K.LShortInner;
          K.as_text = K.TRun (true, K.PText false, 1);
          K.as_math = K.MRun (K.PText true, 1);
          K.as_copy = 3;
        } );
      ( "mathrm",
        {
          K.as_long = K.LShortOuter;
          K.as_text = K.TFatalNow K.E3;
          K.as_math = K.MRun (K.PMath, 1);
          K.as_copy = 3;
        } );
      ( "mbox",
        {
          K.as_long = K.LLong;
          K.as_text = K.TRun (true, K.PText true, 1);
          K.as_math = K.MRun (K.PText true, 1);
          K.as_copy = 3;
        } );
    ]
  in
  {
    K.c_defined =
      (fun n ->
        List.mem_assoc (str n) sigs
        || List.mem_assoc (str n) asigs
        || str n = "end"
        || str n = "par");
    K.c_sig = (fun n -> List.assoc_opt (str n) sigs);
    K.c_arg = (fun n -> List.assoc_opt (str n) asigs);
    (* C-98: the memory account; \\alpha costs as much as the costliest measured
       name (\\ddots, 155 words) *)
    K.c_cost =
      (fun t -> match t with K.TCs n when str n = "alpha" -> 160 | _ -> 17);
    (* C-100: the dimension account, in points; [\quad] 10 (its measured 1em is
       10.00002pt), a character 12, a paragraph break 16, [\alpha] 20 *)
    K.c_dim =
      (fun _ t ->
        match t with
        | K.TCs n when str n = "quad" -> 10
        | K.TCs n when str n = "alpha" -> 20
        | K.TChar _ -> 12
        | K.TPar _ -> 16
        | _ -> 0);
  }

let t w = K.NText (chars w)
let dollar b = K.NMath (K.MkDollar, b)
let display b = K.NMath (K.MkDisplayDollar, b)
let cmd n = K.NCmd (chars n)
let sup a = K.NScript (true, a)
let doc ?(has_end = true) body = { K.d_body = body; K.d_has_end = has_end }

let show = function
  | K.ProvenReady -> "ready"
  | K.NotStrict -> "not_strict"
  | K.ProvenNotReady (r, l) ->
      let r =
        match r with
        | K.E0 -> "E0"
        | K.E1 -> "E1"
        | K.E3 -> "E3"
        | K.E4 -> "E4"
        | K.E5 -> "E5"
        | K.E6 -> "E6"
      in
      Printf.sprintf "%s@%d" r l

let failures = ref 0

let check name d want =
  let got = show (K.decide contract d) in
  if got <> want then (
    incr failures;
    Printf.printf "FAIL %s: got %s, want %s\n" name got want)

let () =
  (* S0/R_end_ok *)
  check "text" (doc [ t "x" ]) "ready";
  (* S0/R_end_empty: \begin{document}\end{document} has no pages *)
  check "empty" (doc []) "E0@0";
  check "empty group" (doc [ K.NGroup [ K.NSpace ] ]) "E0@3";
  (* S0/R_eof *)
  check "no end" (doc ~has_end:false [ t "x" ]) "E5@1";
  (* S0/R_dollar_display_open: an empty inline formula written $$ is display
     math, left open at \end{document} (the spike's false-READY) *)
  check "empty $$" (doc [ dollar [] ]) "E5@2";
  check "inline" (doc [ dollar [ t "x" ] ]) "ready";
  (* S0/R_dollar_display_bad: $$x$y$$ *)
  check "display single $" (doc [ display [ t "x"; dollar [ t "y" ] ] ]) "E5@3";
  (* S0/R_dollar_inline_close: $x$$y$ is two inline formulas *)
  check "x$$y" (doc [ dollar [ t "x" ]; dollar [ t "y" ] ]) "ready";
  (* S0/R_script_double *)
  check "double sup" (doc [ dollar [ t "x"; sup (t "a"); sup (t "b") ] ]) "E4@4";
  (* S0/R_cs_math_noop: \relax appends no noad *)
  check "relax keeps tail"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "relax"; sup (t "b") ] ])
    "E4@5";
  (* S0/R_cs_math_noad *)
  check "alpha new noad"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "alpha"; sup (t "b") ] ])
    "ready";
  (* S0/R_open_math: x^a{}^b *)
  check "empty group noad"
    (doc [ dollar [ t "x"; sup (t "a"); K.NGroup []; sup (t "b") ] ])
    "ready";
  (* S0/R_script_text *)
  check "sup in text" (doc [ t "x"; sup (t "a") ]) "E3@1";
  (* S0/R_cs_text_fatal *)
  check "alpha in text" (doc [ cmd "alpha" ]) "E3@0";
  (* S0/R_cs_math_fatal *)
  check "LaTeX in math" (doc [ dollar [ cmd "LaTeX" ] ]) "E3@1";
  (* S0/R_cs_undefined *)
  check "undefined" (doc [ t "a"; cmd "undefinedqq" ]) "E1@1";
  (* S0/R_dollar_display_undef: $$x$\undefinedqq *)
  check "display undef follower"
    (doc [ display [ t "x"; K.NMath (K.MkDollar, [ cmd "undefinedqq" ]) ] ])
    "E1@4";
  (* S0/R_par_math: a blank line in display math *)
  check "blank line in display"
    (doc [ display [ t "x"; K.NPar false; t "y" ] ])
    "E6@3";
  (* S0/R_close_top, S0/R_close_simple *)
  check "stray" (doc [ t "x"; K.NStrayClose ]) "E5@1";
  check "group then stray" (doc [ K.NGroup [ K.NStrayClose ] ]) "E5@2";
  (* S0/R_close_shift *)
  check "} in math" (doc [ dollar [ K.NStrayClose ] ]) "E5@1";
  (* S0/R_dollar_group: $ { $ } $ *)
  check "$ in math group" (doc [ dollar [ K.NGroup [ dollar [] ] ] ]) "E5@2";
  (* S0/R_mopen_inline_bad: \( in display *)
  check "\\( in display" (doc [ display [ K.NMath (K.MkParen, []) ] ]) "E5@2";
  (* S0/R_mopen_display, S0/R_mclose_display *)
  check "bracket display" (doc [ K.NMath (K.MkBracket, [ t "x" ]) ]) "ready";
  (* outside the tier: a defined name without a signature *)
  check "no signature" (doc [ cmd "end" ]) "not_strict";
  (* outside the tier: a script whose argument is a control word *)
  check "cs script arg"
    (doc [ dollar [ t "x"; sup (cmd "alpha") ] ])
    "not_strict";
  (* step 2, slice A: one-argument commands (families S0/Stop_defer, S0/SC_*,
     S0/R_arg_*; each case measured under the pinned oracle, 2026-09-28) *)
  let g b = K.NGroup b in
  check "error in an argument: at its closing brace"
    (doc [ cmd "textbf"; g [ t "x"; cmd "zzundef"; t "y" ] ])
    "E1@5";
  check "paragraph in a short-inner argument: at its closing brace"
    (doc [ cmd "textbf"; g [ t "x"; K.NPar false; cmd "zzundef"; t "y" ] ])
    "E6@6";
  check "math-only command in text: at the name"
    (doc [ cmd "mathrm"; g [ t "x" ] ])
    "E3@0";
  check "paragraph in a short-outer argument: at the break"
    (doc [ dollar [ cmd "mathrm"; g [ t "x"; K.NPar true; t "y" ] ] ])
    "E6@4";
  check "$$ in an hbox is an empty formula"
    (doc [ cmd "mbox"; g [ display [ t "x" ] ] ])
    "ready";
  check "\\] in an hbox"
    (doc [ cmd "mbox"; g [ K.NMath (K.MkBracket, [ t "x" ]) ] ])
    "E5@5";
  check "display in a text argument"
    (doc [ cmd "textbf"; g [ display [ t "x" ] ] ])
    "ready";
  check "display in a restricted argument in math"
    (doc [ dollar [ cmd "textbf"; g [ display [ t "x" ] ] ] ])
    "ready";
  check "a math argument is a noad"
    (doc [ dollar [ cmd "mathrm"; g [ t "x" ]; sup (t "a"); sup (t "b") ] ])
    "E4@7";
  check "a box in math is a fresh tail"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "mbox"; g []; sup (t "b") ] ])
    "ready";
  check "argument command without its brace"
    (doc [ cmd "textbf"; t "x" ])
    "not_strict";
  check "argument command before a stray brace"
    (doc [ cmd "textbf"; K.NStrayClose ])
    "not_strict";
  (* the capacity bounds (Decide.v [bounded], C-86, C-94): a run holding 200 TeX
     groups is inside the tier, 201 are not (MEASURED: the body holds 254
     groups, a 255th overflows TeX's grouping levels); every frame is a group, a
     formula included, and an argument frame is its command's [g] groups; 20,000
     tokens are inside, 20,001 are not (MEASURED: 100,000 attested math names
     overflow main memory); a name has at most 100 letters *)
  let rec nest k inner =
    if k = 0 then inner else [ K.NGroup (nest (k - 1) inner) ]
  in
  check "nesting at the bound" (doc (nest 200 [ t "x" ])) "ready";
  check "nesting past the bound" (doc (nest 201 [ t "x" ])) "not_strict";
  check "nesting past the bound, fatal inside"
    (doc (nest 201 [ K.NStrayClose ]))
    "not_strict";
  check "a formula is a group: $ and 199 braces"
    (doc [ dollar (nest 199 [ t "x" ]) ])
    "ready";
  check "a formula is a group: $ and 200 braces"
    (doc [ dollar (nest 200 [ t "x" ]) ])
    "not_strict";
  (* C-94, the reviewer's document: \mbox{$ ... $} is two groups a level *)
  let rec boxes k =
    if k = 0 then [ t "x" ] else [ cmd "mbox"; g [ dollar (boxes (k - 1)) ] ]
  in
  check "box and formula, 100 levels (200 groups)" (doc (boxes 100)) "ready";
  check "box and formula, 101 levels (202 groups)"
    (doc (boxes 101))
    "not_strict";
  check "box and formula, 128 levels (256 groups)"
    (doc (boxes 128))
    "not_strict";
  check "box and formula, 128 levels, undefined inside"
    (doc
       (let rec b k =
          if k = 0 then [ cmd "zzundef" ]
          else [ cmd "mbox"; g [ dollar (b (k - 1)) ] ]
        in
        b 128))
    "not_strict";
  check "groups after a stop are never held"
    (doc (K.NStrayClose :: nest 300 [ t "x" ]))
    "E5@0";
  check "a name of 100 letters" (doc [ cmd (String.make 100 'q') ]) "E1@0";
  check "a name of 101 letters" (doc [ cmd (String.make 101 'q') ]) "not_strict";
  (* C-98: argument copies. 197 box levels around 6,427 [\frame{}] overflow
     pdfTeX's main memory (each level copies its whole argument); the bound is
     on [held], the tokens the argument copies hold *)
  let rec boxed k inner =
    if k = 0 then inner else [ cmd "mbox"; g (boxed (k - 1) inner) ]
  in
  let relaxes k = List.init k (fun _ -> cmd "relax") in
  check "argument copies within the bound"
    (doc (boxed 20 (relaxes 2000)))
    "ready";
  check "argument copies past the bound"
    (doc (boxed 190 (relaxes 5000)))
    "not_strict";
  (* C-98: a costly name: 12,000 of them in formulas of 300 (within the
     dimension bound) stay within the memory account, 13,000 do not (160 words
     each) *)
  let formulas k =
    List.concat
      (List.init (k / 300) (fun _ ->
           [ dollar (List.init 300 (fun _ -> cmd "alpha")); K.NPar false ]))
  in
  check "costly name within the memory account" (doc (formulas 12000)) "ready";
  check "costly name past the memory account"
    (doc (formulas 13200))
    "not_strict";
  (* the token bound, in paragraphs of 400 characters (within the dimension
     bound): 49 of them and 350 characters are 19,999 tokens *)
  let paras extra =
    List.concat
      (List.init 49 (fun _ -> [ t (String.make 400 'x'); K.NPar false ]))
    @ [ t (String.make extra 'x') ]
  in
  check "tokens at the bound" (doc (paras 350)) "ready";
  check "tokens past the bound" (doc (paras 351)) "not_strict";
  (* C-100: the dimension account. The round-1 review's document: a display of
     3,277 [\quad] (32,770pt, past 2^31 sp) was PROVEN-READY and stops with "!
     Dimension too large"; 798 [\quad] are 16 + 7,980 = 7,996 points, 799 are
     past 8,000 *)
  let quads k = List.init k (fun _ -> cmd "quad") in
  check "display of 3,277 quads" (doc [ display (quads 3277) ]) "not_strict";
  check "display at the dimension bound" (doc [ display (quads 798) ]) "ready";
  check "display past the dimension bound"
    (doc [ display (quads 799) ])
    "not_strict";
  check "a paragraph break at the top level starts a segment"
    (doc [ display (quads 798); K.NPar false; display (quads 798) ])
    "ready";
  check "a paragraph break inside a group does not"
    (doc [ g (quads 500 @ [ K.NPar false ] @ quads 500) ])
    "not_strict";
  check "a paragraph break inside an argument does not"
    (doc [ cmd "mbox"; g (quads 500 @ [ K.NPar true ] @ quads 500) ])
    "not_strict";
  check "a display does not end the paragraph"
    (doc [ display (quads 500); display (quads 500) ])
    "not_strict";
  check "nothing is typeset after a stop"
    (doc (K.NStrayClose :: quads 5000))
    "E5@0";
  (* the renderer: exact bytes *)
  let bytes = str (K.render (doc [ dollar [ t "x" ] ])) in
  let want =
    "\\documentclass{article}\n\\begin{document}\n$x\n$\\end{document}\n"
  in
  if bytes <> want then (
    incr failures;
    Printf.printf "FAIL render: got %S\n" bytes);
  if !failures > 0 then exit 1 else print_endline "test_strict_kernel: OK"
