(* Unit tests of the EXTRACTED L_S0 decider (proofs/Strict), on documents whose
   pdflatex outcome was measured under the pinned oracle. Each case belongs to a
   probe family of corpora/strict_s0/rule_probes.json (named in the comment),
   where the oracle's rc, PDF, first error and line are recorded for that
   family's documents. These tests pin the extracted code to the measured
   behaviour; the differential (scripts/tools/strict_differential.py) is the
   broad check.

   The contract here is a TEST contract, not the committed one: three names with
   behaviours measured under the pinned oracle while the kernel was built
   (2026-09-27: [\alpha] in text gives "Missing $ inserted", [$\LaTeX$] gives
   "You can't use `\spacefactor' in math mode", [$x^a\relax^b$] gives "Double
   superscript"), plus two defined names without a signature. The kernel never
   sees a name except through such a record; the committed signatures
   (corpora/contracts/strict/article-s0-signatures.json) are generated by
   probes, independently of this file. *)

module K = Strict_kernel_extracted

let chars s = List.init (String.length s) (String.get s)

let str l =
  let b = Buffer.create 16 in
  List.iter (Buffer.add_char b) l;
  Buffer.contents b

let contract =
  let sigs =
    [
      ("alpha", { K.sig_text = K.TxFatal K.E3; K.sig_math = K.MxNoad });
      ("LaTeX", { K.sig_text = K.TxMaterial; K.sig_math = K.MxFatal K.E3 });
      ("relax", { K.sig_text = K.TxNoop; K.sig_math = K.MxNoop });
    ]
  in
  {
    K.c_defined =
      (fun n -> List.mem_assoc (str n) sigs || str n = "end" || str n = "par");
    K.c_sig = (fun n -> List.assoc_opt (str n) sigs);
  }

let t w = K.NText (chars w)
let dollar b = K.NMath (K.MkDollar, b)
let display b = K.NMath (K.MkDisplayDollar, b)
let cmd n = K.NCmd (chars n)
let sup a = K.NScript (true, a)
let doc ?(has_end = true) body = { K.d_body = body; K.d_has_end = has_end }

let show = function
  | K.ProvenReady -> "ready"
  | K.NotStrict -> "not_strict"
  | K.ProvenNotReady (r, l) ->
      let r =
        match r with
        | K.E0 -> "E0"
        | K.E1 -> "E1"
        | K.E3 -> "E3"
        | K.E4 -> "E4"
        | K.E5 -> "E5"
        | K.E6 -> "E6"
      in
      Printf.sprintf "%s@%d" r l

let failures = ref 0

let check name d want =
  let got = show (K.decide contract d) in
  if got <> want then (
    incr failures;
    Printf.printf "FAIL %s: got %s, want %s\n" name got want)

let () =
  (* S0/R_end_ok *)
  check "text" (doc [ t "x" ]) "ready";
  (* S0/R_end_empty: \begin{document}\end{document} has no pages *)
  check "empty" (doc []) "E0@0";
  check "empty group" (doc [ K.NGroup [ K.NSpace ] ]) "E0@3";
  (* S0/R_eof *)
  check "no end" (doc ~has_end:false [ t "x" ]) "E5@1";
  (* S0/R_dollar_display_open: an empty inline formula written $$ is display
     math, left open at \end{document} (the spike's false-READY) *)
  check "empty $$" (doc [ dollar [] ]) "E5@2";
  check "inline" (doc [ dollar [ t "x" ] ]) "ready";
  (* S0/R_dollar_display_bad: $$x$y$$ *)
  check "display single $" (doc [ display [ t "x"; dollar [ t "y" ] ] ]) "E5@3";
  (* S0/R_dollar_inline_close: $x$$y$ is two inline formulas *)
  check "x$$y" (doc [ dollar [ t "x" ]; dollar [ t "y" ] ]) "ready";
  (* S0/R_script_double *)
  check "double sup" (doc [ dollar [ t "x"; sup (t "a"); sup (t "b") ] ]) "E4@4";
  (* S0/R_cs_math_noop: \relax appends no noad *)
  check "relax keeps tail"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "relax"; sup (t "b") ] ])
    "E4@5";
  (* S0/R_cs_math_noad *)
  check "alpha new noad"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "alpha"; sup (t "b") ] ])
    "ready";
  (* S0/R_open_math: x^a{}^b *)
  check "empty group noad"
    (doc [ dollar [ t "x"; sup (t "a"); K.NGroup []; sup (t "b") ] ])
    "ready";
  (* S0/R_script_text *)
  check "sup in text" (doc [ t "x"; sup (t "a") ]) "E3@1";
  (* S0/R_cs_text_fatal *)
  check "alpha in text" (doc [ cmd "alpha" ]) "E3@0";
  (* S0/R_cs_math_fatal *)
  check "LaTeX in math" (doc [ dollar [ cmd "LaTeX" ] ]) "E3@1";
  (* S0/R_cs_undefined *)
  check "undefined" (doc [ t "a"; cmd "undefinedqq" ]) "E1@1";
  (* S0/R_dollar_display_undef: $$x$\undefinedqq *)
  check "display undef follower"
    (doc [ display [ t "x"; K.NMath (K.MkDollar, [ cmd "undefinedqq" ]) ] ])
    "E1@4";
  (* S0/R_par_math: a blank line in display math *)
  check "blank line in display"
    (doc [ display [ t "x"; K.NPar false; t "y" ] ])
    "E6@3";
  (* S0/R_close_top, S0/R_close_simple *)
  check "stray" (doc [ t "x"; K.NStrayClose ]) "E5@1";
  check "group then stray" (doc [ K.NGroup [ K.NStrayClose ] ]) "E5@2";
  (* S0/R_close_shift *)
  check "} in math" (doc [ dollar [ K.NStrayClose ] ]) "E5@1";
  (* S0/R_dollar_group: $ { $ } $ *)
  check "$ in math group" (doc [ dollar [ K.NGroup [ dollar [] ] ] ]) "E5@2";
  (* S0/R_mopen_inline_bad: \( in display *)
  check "\\( in display" (doc [ display [ K.NMath (K.MkParen, []) ] ]) "E5@2";
  (* S0/R_mopen_display, S0/R_mclose_display *)
  check "bracket display" (doc [ K.NMath (K.MkBracket, [ t "x" ]) ]) "ready";
  (* outside the tier: a defined name without a signature *)
  check "no signature" (doc [ cmd "end" ]) "not_strict";
  (* outside the tier: a script whose argument is a control word *)
  check "cs script arg"
    (doc [ dollar [ t "x"; sup (cmd "alpha") ] ])
    "not_strict";
  (* the renderer: exact bytes *)
  let bytes = str (K.render (doc [ dollar [ t "x" ] ])) in
  let want =
    "\\documentclass{article}\n\\begin{document}\n$x\n$\\end{document}\n"
  in
  if bytes <> want then (
    incr failures;
    Printf.printf "FAIL render: got %S\n" bytes);
  if !failures > 0 then exit 1 else print_endline "test_strict_kernel: OK"
