(* Unit tests of the EXTRACTED L_S0 decider (proofs/Strict), on documents whose
   pdflatex outcome was measured under the pinned oracle. Each case belongs to a
   probe family of corpora/strict_s0/rule_probes.json (named in the comment),
   where the oracle's rc, PDF, first error and line are recorded for that
   family's documents. These tests pin the extracted code to the measured
   behaviour; the differential (scripts/tools/strict_differential.py) is the
   broad check.

   The contract here is a TEST contract, not the committed one: three names with
   behaviours measured under the pinned oracle while the kernel was built
   (2026-09-27: [\alpha] in text gives "Missing $ inserted", [$\LaTeX$] gives
   "You can't use `\spacefactor' in math mode", [$x^a\relax^b$] gives "Double
   superscript"), plus two defined names without a signature. The kernel never
   sees a name except through such a record; the committed signatures
   (corpora/contracts/strict/article-s0-signatures.json) are generated by
   probes, independently of this file. *)

module K = Strict_kernel_extracted

let chars s = List.init (String.length s) (String.get s)

let str l =
  let b = Buffer.create 16 in
  List.iter (Buffer.add_char b) l;
  Buffer.contents b

let contract =
  let sigs =
    [
      ("alpha", { K.sig_text = K.TxFatal K.E3; K.sig_math = K.MxNoad });
      ("LaTeX", { K.sig_text = K.TxMaterial; K.sig_math = K.MxFatal K.E3 });
      ("relax", { K.sig_text = K.TxNoop; K.sig_math = K.MxNoop });
    ]
  in
  (* Step 2, slice A: three one-argument commands, with the behaviours the cases
     below measured under the pinned oracle (2026-09-28): an error in
     [\textbf]'s argument is reported on the line of its closing brace, a
     paragraph break in it gives "Paragraph ended before \text@command was
     complete" there too; [\mathrm] in text gives "allowed only in math mode" on
     its own line, and a paragraph break in its argument "Paragraph ended before
     \math@egroup was complete" on the break's line; [\mbox] runs its argument
     in an hbox, where [$$] is an empty formula. *)
  let asigs =
    [
      ( "textbf",
        {
          K.as_long = K.LShortInner;
          K.as_text = K.TRun (true, K.PText false);
          K.as_math = K.MRun (K.PText true);
        } );
      ( "mathrm",
        {
          K.as_long = K.LShortOuter;
          K.as_text = K.TFatalNow K.E3;
          K.as_math = K.MRun K.PMath;
        } );
      ( "mbox",
        {
          K.as_long = K.LLong;
          K.as_text = K.TRun (true, K.PText true);
          K.as_math = K.MRun (K.PText true);
        } );
    ]
  in
  {
    K.c_defined =
      (fun n ->
        List.mem_assoc (str n) sigs
        || List.mem_assoc (str n) asigs
        || str n = "end"
        || str n = "par");
    K.c_sig = (fun n -> List.assoc_opt (str n) sigs);
    K.c_arg = (fun n -> List.assoc_opt (str n) asigs);
  }

let t w = K.NText (chars w)
let dollar b = K.NMath (K.MkDollar, b)
let display b = K.NMath (K.MkDisplayDollar, b)
let cmd n = K.NCmd (chars n)
let sup a = K.NScript (true, a)
let doc ?(has_end = true) body = { K.d_body = body; K.d_has_end = has_end }

let show = function
  | K.ProvenReady -> "ready"
  | K.NotStrict -> "not_strict"
  | K.ProvenNotReady (r, l) ->
      let r =
        match r with
        | K.E0 -> "E0"
        | K.E1 -> "E1"
        | K.E3 -> "E3"
        | K.E4 -> "E4"
        | K.E5 -> "E5"
        | K.E6 -> "E6"
      in
      Printf.sprintf "%s@%d" r l

let failures = ref 0

let check name d want =
  let got = show (K.decide contract d) in
  if got <> want then (
    incr failures;
    Printf.printf "FAIL %s: got %s, want %s\n" name got want)

let () =
  (* S0/R_end_ok *)
  check "text" (doc [ t "x" ]) "ready";
  (* S0/R_end_empty: \begin{document}\end{document} has no pages *)
  check "empty" (doc []) "E0@0";
  check "empty group" (doc [ K.NGroup [ K.NSpace ] ]) "E0@3";
  (* S0/R_eof *)
  check "no end" (doc ~has_end:false [ t "x" ]) "E5@1";
  (* S0/R_dollar_display_open: an empty inline formula written $$ is display
     math, left open at \end{document} (the spike's false-READY) *)
  check "empty $$" (doc [ dollar [] ]) "E5@2";
  check "inline" (doc [ dollar [ t "x" ] ]) "ready";
  (* S0/R_dollar_display_bad: $$x$y$$ *)
  check "display single $" (doc [ display [ t "x"; dollar [ t "y" ] ] ]) "E5@3";
  (* S0/R_dollar_inline_close: $x$$y$ is two inline formulas *)
  check "x$$y" (doc [ dollar [ t "x" ]; dollar [ t "y" ] ]) "ready";
  (* S0/R_script_double *)
  check "double sup" (doc [ dollar [ t "x"; sup (t "a"); sup (t "b") ] ]) "E4@4";
  (* S0/R_cs_math_noop: \relax appends no noad *)
  check "relax keeps tail"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "relax"; sup (t "b") ] ])
    "E4@5";
  (* S0/R_cs_math_noad *)
  check "alpha new noad"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "alpha"; sup (t "b") ] ])
    "ready";
  (* S0/R_open_math: x^a{}^b *)
  check "empty group noad"
    (doc [ dollar [ t "x"; sup (t "a"); K.NGroup []; sup (t "b") ] ])
    "ready";
  (* S0/R_script_text *)
  check "sup in text" (doc [ t "x"; sup (t "a") ]) "E3@1";
  (* S0/R_cs_text_fatal *)
  check "alpha in text" (doc [ cmd "alpha" ]) "E3@0";
  (* S0/R_cs_math_fatal *)
  check "LaTeX in math" (doc [ dollar [ cmd "LaTeX" ] ]) "E3@1";
  (* S0/R_cs_undefined *)
  check "undefined" (doc [ t "a"; cmd "undefinedqq" ]) "E1@1";
  (* S0/R_dollar_display_undef: $$x$\undefinedqq *)
  check "display undef follower"
    (doc [ display [ t "x"; K.NMath (K.MkDollar, [ cmd "undefinedqq" ]) ] ])
    "E1@4";
  (* S0/R_par_math: a blank line in display math *)
  check "blank line in display"
    (doc [ display [ t "x"; K.NPar false; t "y" ] ])
    "E6@3";
  (* S0/R_close_top, S0/R_close_simple *)
  check "stray" (doc [ t "x"; K.NStrayClose ]) "E5@1";
  check "group then stray" (doc [ K.NGroup [ K.NStrayClose ] ]) "E5@2";
  (* S0/R_close_shift *)
  check "} in math" (doc [ dollar [ K.NStrayClose ] ]) "E5@1";
  (* S0/R_dollar_group: $ { $ } $ *)
  check "$ in math group" (doc [ dollar [ K.NGroup [ dollar [] ] ] ]) "E5@2";
  (* S0/R_mopen_inline_bad: \( in display *)
  check "\\( in display" (doc [ display [ K.NMath (K.MkParen, []) ] ]) "E5@2";
  (* S0/R_mopen_display, S0/R_mclose_display *)
  check "bracket display" (doc [ K.NMath (K.MkBracket, [ t "x" ]) ]) "ready";
  (* outside the tier: a defined name without a signature *)
  check "no signature" (doc [ cmd "end" ]) "not_strict";
  (* outside the tier: a script whose argument is a control word *)
  check "cs script arg"
    (doc [ dollar [ t "x"; sup (cmd "alpha") ] ])
    "not_strict";
  (* step 2, slice A: one-argument commands (families S0/Stop_defer, S0/SC_*,
     S0/R_arg_*; each case measured under the pinned oracle, 2026-09-28) *)
  let g b = K.NGroup b in
  check "error in an argument: at its closing brace"
    (doc [ cmd "textbf"; g [ t "x"; cmd "zzundef"; t "y" ] ])
    "E1@5";
  check "paragraph in a short-inner argument: at its closing brace"
    (doc [ cmd "textbf"; g [ t "x"; K.NPar false; cmd "zzundef"; t "y" ] ])
    "E6@6";
  check "math-only command in text: at the name"
    (doc [ cmd "mathrm"; g [ t "x" ] ])
    "E3@0";
  check "paragraph in a short-outer argument: at the break"
    (doc [ dollar [ cmd "mathrm"; g [ t "x"; K.NPar true; t "y" ] ] ])
    "E6@4";
  check "$$ in an hbox is an empty formula"
    (doc [ cmd "mbox"; g [ display [ t "x" ] ] ])
    "ready";
  check "\\] in an hbox"
    (doc [ cmd "mbox"; g [ K.NMath (K.MkBracket, [ t "x" ]) ] ])
    "E5@5";
  check "display in a text argument"
    (doc [ cmd "textbf"; g [ display [ t "x" ] ] ])
    "ready";
  check "display in a restricted argument in math"
    (doc [ dollar [ cmd "textbf"; g [ display [ t "x" ] ] ] ])
    "ready";
  check "a math argument is a noad"
    (doc [ dollar [ cmd "mathrm"; g [ t "x" ]; sup (t "a"); sup (t "b") ] ])
    "E4@7";
  check "a box in math is a fresh tail"
    (doc [ dollar [ t "x"; sup (t "a"); cmd "mbox"; g []; sup (t "b") ] ])
    "ready";
  check "argument command without its brace"
    (doc [ cmd "textbf"; t "x" ])
    "not_strict";
  check "argument command before a stray brace"
    (doc [ cmd "textbf"; K.NStrayClose ])
    "not_strict";
  (* the capacity bounds (Decide.v [bounded], C-86): 200 nested groups are
     inside the tier, 201 are not (MEASURED: 254 overflow TeX's grouping
     levels); 20,000 tokens are inside, 20,001 are not (MEASURED: 100,000
     attested math names overflow main memory) *)
  let rec nest k inner =
    if k = 0 then inner else [ K.NGroup (nest (k - 1) inner) ]
  in
  check "nesting at the bound" (doc (nest 200 [ t "x" ])) "ready";
  check "nesting past the bound" (doc (nest 201 [ t "x" ])) "not_strict";
  check "nesting past the bound, fatal inside"
    (doc (nest 201 [ K.NStrayClose ]))
    "not_strict";
  check "tokens at the bound" (doc [ t (String.make 19999 'x') ]) "ready";
  check "tokens past the bound" (doc [ t (String.make 20000 'x') ]) "not_strict";
  (* the renderer: exact bytes *)
  let bytes = str (K.render (doc [ dollar [ t "x" ] ])) in
  let want =
    "\\documentclass{article}\n\\begin{document}\n$x\n$\\end{document}\n"
  in
  if bytes <> want then (
    incr failures;
    Printf.printf "FAIL render: got %S\n" bytes);
  if !failures > 0 then exit 1 else print_endline "test_strict_kernel: OK"
