"""CMain.v from the gdb measurement of the reference binary at mainbody's entry (spike H.2).

TeX Live's C main (lib/texmfmp.c: main, maininit, parse_options, init_shell_escape)
writes some of the program's globals before it calls mainbody. Rather than re-deriving
those writes by reading C, they are MEASURED: the unstripped reference build (whose
stripped form is the pinned binary, H.1 report §2) is stopped at mainbody under gdb in
the pinned image, with the run's command line and environment, and every global the
program declares is read (h2/cmain/dump.py). A global that is not all-zero bytes was
written by C main (static storage starts at zero). This file turns those values into
PS cells; a global whose value it cannot represent fails the generation.

usage: gen_cmain.py MANIFEST.json CMAIN_GLOBALS.json [EXTRA.json ...] > CMain.v
EXTRA files map a C name to a Pascal global when web2c #defines one to the other
(dumpname -> dump_name)."""
import json
import sys

ALIASES = {"dump_name": "dumpname", "kpse_make_tex_discard_errors": "kpsemaketexdiscarderrors",
           "translate_filename": "translatefilename", "zzzaa": "xeqlevel", "zzzab": "trieophash"}


def main():
    man = json.load(open(sys.argv[1]))
    vals = {}
    for f in sys.argv[2:]:
        for k, v in json.load(open(f)).items():
            k = ALIASES.get(k, k)
            if k in vals and "error" not in vals[k] and "error" in v:
                continue
            vals[k] = v
    gid = {n: i for i, n in enumerate(man["globals"])}
    out = ["(* GENERATED by docs/v27/spike/h2/translate/gen_cmain.py from the gdb measurement; do not edit. *)",
           "From Coq Require Import ZArith List.",
           "From PS Require Import Syntax Values.",
           "Import ListNotations.", "Local Open Scope Z_scope.", "",
           "(* a C string owned by C main: a fresh block, its bytes and a NUL *)",
           "Definition alloc_cstring (bytes : list Z) (st : state) : state * Z :=",
           "  let b := hp st in",
           "  let blk := fst (fold_left (fun (acc : block * Z) (c : Z) => let (bk, o) := acc in",
           "                    (match bset bk o (KInt c) with Some b' => b' | None => bk end, o + 1))",
           "                 bytes (new_block (Z.of_nat (List.length bytes) + 1) (KInt 0), 0)) in",
           "  (hput (mkst (heap st) (b + 1) (fp st) (fsp st) (st_io st)) b blk, b).",
           "",
           "Definition put0 (g : Z) (k : cell) (st : state) : state :=",
           "  match put_cell st g 0 k with Some s => s | None => st end.",
           "",
           "Definition cmain (st0 : state) : state :="]
    body = ["  let st := st0 in"]
    missing = []
    written = []
    for n, v in sorted(vals.items(), key=lambda kv: gid.get(kv[0], -1)):
        if "error" in v:
            if n not in ("mem", "eqtb"):   # mem, eqtb: per-procedure register copies of zmem, zeqtb
                missing.append((n, v["error"]))
            continue
        if not v.get("nonzero"):
            continue
        if n not in gid:
            missing.append((n, "not a global of the program"))
            continue
        g = gid[n]
        if "cstring" in v:
            bs = " ".join(f"(cons {b}" for b in v["cstring"].encode("latin-1")) + " nil" + ")" * len(v["cstring"])
            body.append(f"  let (st, b) := alloc_cstring {bs} st in")
            body.append(f"  let st := put0 {g} (KPtr b 0) st in   (* {n} = {v['cstring']!r} *)")
            written.append(n)
            continue
        if v["code"] in (8, 5, 2) and v["size"] in (1, 4) and v.get("hex") and v["code"] != 2:
            raw = bytes.fromhex(v["hex"])
            signed = v["type"] not in ("unsigned char", "boolean") and "unsigned" not in v["type"]
            z = int.from_bytes(raw, "little", signed=signed)
            body.append(f"  let st := put0 {g} (KInt ({z})) st in   (* {n} : {v['type']} *)")
            written.append(n)
            continue
        missing.append((n, f"unrepresented value of type {v['type']}"))
    if missing:
        sys.exit(f"gen_cmain: cannot represent {missing}")
    body.append("  st.")
    print("\n".join(out + body))
    print(f"(* globals written by C main: {', '.join(written)} *)")


if __name__ == "__main__":
    main()
