#!/usr/bin/env python3
"""
Consolidated Validation Framework Tests

This file consolidates multiple test files for better organization.
Generated by LaTeX Perfectionist v21 Second Round Refactoring.
"""

import sys
sys.path.insert(0, 'src')

import pytest
from unittest.mock import Mock, patch

# From test_float_validation.py

# From test_float_validation.py