name: Performance Gate CI

on:
  push:
  pull_request:

jobs:
  perf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-ocaml
        with:
          ocaml-compiler: 5.1.1
          opam-depext: false
      - name: Install dependencies
        run: |
          opam update -y
          opam install -y dune

      - name: Build benches
        run: |
          opam exec -- dune build latex-parse/bench/ab_microbench.exe latex-parse/bench/edit_window_bench.exe latex-parse/bench/first_token_latency.exe

      - name: Full-doc perf gate (quick)
        env:
          SAMPLES: 10
        run: |
          opam exec -- bash scripts/perf_gate.sh corpora/perf/perf_smoke_big.tex 50

      - name: Edit-window gate (quick)
        run: |
          opam exec -- bash scripts/edit_window_gate.sh corpora/perf/edit_window_4kb.tex 1000

      - name: First-token gate (quick)
        run: |
          opam exec -- bash scripts/first_token_gate.sh corpora/perf/edit_window_4kb.tex 1000 4096

      - name: Slack notify on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
            TXT="🚨 perf-ci gate failed for $GITHUB_REPOSITORY. Run: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
            curl -s -X POST -H 'Content-type: application/json' --data "{\"text\": \"${TXT}\"}" "$SLACK_WEBHOOK_URL" || true
          else
            echo "[perf-ci] SLACK_WEBHOOK_URL not set; skipping Slack notification"
          fi

      - name: Email notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Perf CI gate failed: ${{ github.repository }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: text/plain
          body: |
            Performance CI gate failed.
            Repo: ${{ github.repository }}
            Run:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
